//! Early-exit sites nothing executes. The extractor, the generated report's digest and the
//! three pins live in `dev/pytools/error_sites.py`; `docs/error-sites.md` is its output.

fn error_sites(arg: &str) -> std::process::Output {
    std::process::Command::new("python3")
        .args(["dev/pytools/error_sites.py", arg])
        .current_dir(env!("CARGO_MANIFEST_DIR"))
        .output()
        .expect("python3 is a prerequisite of every gate script in this repo")
}

#[test]
fn the_extractor_grades_its_own_fixture() {
    let out = error_sites("--self-test");
    assert_eq!(
        String::from_utf8_lossy(&out.stdout).trim(),
        "error_sites self-test: ok",
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
}

#[test]
fn the_committed_report_is_the_generated_one_and_holds_its_ceilings() {
    let out = error_sites("check");
    let said = String::from_utf8_lossy(&out.stdout);
    assert_eq!(
        (out.status.code(), said.contains("ERROR-SITES")),
        (Some(0), false),
        "docs/error-sites.md is generated by `make error-sites`; its numbers are pinned in \
         dev/pytools/error_sites.py and move only with a regenerated report:\n{said}{}",
        String::from_utf8_lossy(&out.stderr)
    );
}
