#!/usr/bin/env python3
"""Generate the config reference (markdown) from `rivet schema config`.

Single source of truth: the JSON Schema the binary emits (schemars ← the Rust
Config types). Run:  `rivet schema config | python3 dev/docgen/config_md.py`.
The output cannot drift from ExportMode / DestinationType / SourceType / the
`*Config` structs — a CI gate diffs it against the committed reference.
"""
import json
import sys

BLOCK = "<!-- GENERATED by dev/docgen/config_md.py from `rivet schema config` — DO NOT EDIT BY HAND. -->"

def load():
    data = sys.stdin.read() if not sys.stdin.isatty() else open(sys.argv[1]).read()
    return json.loads(data)

def enum_values(defs, node):
    """Return the list of literal string values a node accepts (plain enum OR a
    oneOf/anyOf of consts — the schemars representation of a fieldless enum whose
    variants carry data, e.g. source.type=mongo / mode=cdc)."""
    vals = []
    if isinstance(node, dict):
        if isinstance(node.get("enum"), list):
            vals += [v for v in node["enum"] if isinstance(v, str)]
        if isinstance(node.get("const"), str):
            vals.append(node["const"])
        for k in ("oneOf", "anyOf", "allOf"):
            for sub in node.get(k, []):
                vals += enum_values(defs, sub)
        ref = node.get("$ref")
        if ref:
            vals += enum_values(defs, defs.get(ref.split("/")[-1], {}))
    return list(dict.fromkeys(vals))  # dedupe, preserve order

def type_str(defs, prop):
    """Human-readable type for a property node."""
    if not isinstance(prop, dict):
        return "—"
    # option / nullable often shows as anyOf[T, null] or type:[T,'null']
    ref = prop.get("$ref")
    if ref:
        name = ref.split("/")[-1]
        target = defs.get(name, {})
        ev = enum_values(defs, target)
        if ev:
            return " \\| ".join(f"`{v}`" for v in ev)
        return f"[{name}](#{name.lower()})"
    ev = enum_values(defs, prop)
    if ev:
        return " \\| ".join(f"`{v}`" for v in ev)
    t = prop.get("type")
    if isinstance(t, list):
        t = " \\| ".join(x for x in t if x != "null")
    if t == "array":
        it = prop.get("items", {})
        return f"array of {type_str(defs, it)}"
    for k in ("anyOf", "oneOf"):
        if k in prop:
            parts = [type_str(defs, s) for s in prop[k] if s.get("type") != "null"]
            return " \\| ".join(dict.fromkeys(parts))
    return f"`{t}`" if t else "object"

def desc(prop):
    d = (prop.get("description") or "").strip().replace("\n", " ")
    return d

def render_object(defs, name, node, title=None):
    props = node.get("properties") or {}
    if not props:
        return ""
    required = set(node.get("required") or [])
    out = [f"### {title or name}", ""]
    out.append("| Field | Type | Required | Description |")
    out.append("|-------|------|:--------:|-------------|")
    for field, p in props.items():
        req = "**yes**" if field in required else ""
        out.append(f"| `{field}` | {type_str(defs, p)} | {req} | {desc(p)} |")
    out.append("")
    return "\n".join(out)

def main():
    s = load()
    defs = s.get("$defs") or s.get("definitions") or {}
    v = s.get("title", "").split("rivet-cli ")[-1].rstrip(")") if "rivet-cli" in s.get("title", "") else "?"

    out = [BLOCK, "",
           f"# Config reference (generated — rivet-cli {v})", "",
           "Rendered from the JSON Schema `rivet schema config` emits (schemars ← "
           "the Rust `Config` types). It cannot drift from the code. Hand-written "
           "guidance lives in the surrounding config guide; **this table set is "
           "generated** — edit the Rust structs, not this block.", ""]

    # Top-level, then the key nested defs in reading order.
    top = {"type": "object", "properties": s.get("properties", {}), "required": s.get("required", [])}
    out.append(render_object(defs, "Top level", top, title="Top level (`rivet.yaml`)"))
    for name, title in [
        ("SourceConfig", "`source`"),
        ("MongoConfig", "`source.mongo` (MongoDB read options)"),
        ("TlsConfig", "`source.tls`"),
        ("ExportConfig", "`exports[]`"),
        ("CdcExportConfig", "`exports[].cdc` (mode: cdc)"),
        ("TuningConfig", "`exports[].tuning`"),
        ("DestinationConfig", "`exports[].destination`"),
        ("QualityConfig", "`exports[].quality`"),
        ("ParquetConfig", "`exports[].parquet`"),
    ]:
        node = defs.get(name)
        if node:
            block = render_object(defs, name, node, title=title)
            if block:
                out.append(block)

    print("\n".join(out).rstrip() + "\n")

if __name__ == "__main__":
    main()
