-- seeds/common/oracle.sql — SELF-CONTAINED canonical seed (DDL + data + garbage).
-- Oracle Database 23ai+ (Free: gvenzl/oracle-free:23-slim). A table-for-table port
-- of seeds/common/mysql.sql; the garbage section mirrors dev/garbage/oracle.sql.
-- Run as the schema owner: sqlplus -s rivet/rivet@//host/FREEPDB1 < seeds/common/oracle.sql
-- Idempotent (DROP … IF EXISTS … PURGE, 23ai syntax); aborts on the first error.
--
-- Deviations from seeds/common/mysql.sql — each is Oracle having no exact equivalent:
--
-- Types
--   * TINYINT → NUMBER(3), SMALLINT → NUMBER(5), INT → NUMBER(10), BIGINT → NUMBER(19).
--     MySQL's signed ranges are not enforced (only the digit count is).
--   * UNSIGNED (TINYINT/SMALLINT/INT/BIGINT) → NUMBER(p) + CHECK (0 ..= max unsigned).
--     BIGINT UNSIGNED → NUMBER(20): 18446744073709551615 is stored exactly.
--   * TINYINT(1) (c_bool) → NUMBER(1) CHECK IN (0,1); BOOLEAN (is_active, is_bounce,
--     c_boolean) → native BOOLEAN (23ai). MySQL's BOOLEAN is TINYINT(1), so Oracle
--     distinguishes the two where MySQL cannot.
--   * DECIMAL(p,s) → NUMBER(p,s). FLOAT → BINARY_FLOAT, DOUBLE → BINARY_DOUBLE.
--   * DATE → DATE. Oracle DATE always carries a time of day (here 00:00:00).
--   * TIME(6) → INTERVAL DAY(0) TO SECOND(6) (Oracle has no time-of-day type).
--   * DATETIME → TIMESTAMP(0), DATETIME(6) → TIMESTAMP(6) (both naive).
--   * TIMESTAMP(6) (MySQL: UTC-stored, rendered in the session zone) →
--     TIMESTAMP(6) WITH LOCAL TIME ZONE — same semantics. Seeded with an explicit
--     +00:00 literal, matching MySQL's `SET time_zone = '+00:00'` before the insert.
--   * DEFAULT CURRENT_TIMESTAMP on a DATETIME → DEFAULT LOCALTIMESTAMP.
--   * TEXT → VARCHAR2(4000) (all seeded values fit; MySQL TEXT's 64 KiB ceiling is
--     not reproduced). LONGTEXT/MEDIUMTEXT (content_items.body/raw_html,
--     long_text, medium_text) → CLOB, since they exceed the 4000-byte VARCHAR2
--     limit under max_string_size=STANDARD.
--   * CHAR(n) → CHAR(n). MySQL strips trailing spaces from CHAR on read
--     ('char-a    ' reads 'char-a'); Oracle returns the blank-padded value.
--   * BINARY(4) → RAW(4). MySQL right-pads BINARY with 0x00, so the stored values
--     are seeded pre-padded: UNHEX('cafe') → CAFE0000, UNHEX('00') → 00000000.
--   * VARBINARY(8) → RAW(8); BLOB → BLOB. UNHEX('') (zero-length, NOT NULL) →
--     EMPTY_BLOB(), which is zero-length and NOT NULL in Oracle too.
--   * JSON → native JSON (23ai). JSON_OBJECT/JSON_ARRAY build the same documents
--     ({"seed":true,"i":1}, ["a","b"], {} …); Oracle may serialize key order/spacing
--     differently.
--   * ENUM('a','b','c') → VARCHAR2(1) + CHECK IN. SET('x','y','z') → VARCHAR2(5)
--     + CHECK over the canonical member combinations. YEAR → NUMBER(4) + CHECK
--     (1901..2155, MySQL's YEAR range). BIT(1) → NUMBER(1) CHECK IN (0,1);
--     BIT(8) → NUMBER(3) CHECK 0..255 (numeric value, as MySQL's b'…' reads back).
--   * AUTO_INCREMENT → GENERATED BY DEFAULT ON NULL AS IDENTITY. The fill inserts
--     id = i explicitly (MySQL's CTE fill yields id = i), then the identity is moved
--     past the max with START WITH LIMIT VALUE so later inserts do not collide.
--   * ENGINE/CHARSET clauses dropped (DB charset is AL32UTF8).
--   * rivet_type_matrix.uid: UID is an Oracle RESERVED WORD (ORA-03050), so the
--     column is the quoted identifier "UID" (catalog name UID, like every other
--     column). A reader must quote it; this is the one quoted identifier here.
--
-- Values
--   * EMPTY STRING IS NULL IN ORACLE. row_hash_probe row 4 seeds a = '' in MySQL;
--     here it arrives as NULL, so rows 3 and 4 are IDENTICAL (a NULL, b 'x'). That
--     is expected Oracle semantics, not a seeding bug — the "absent vs zero-length"
--     distinction cannot be expressed in an Oracle VARCHAR2.
--   * RAND(i) has no reproducible Oracle counterpart. users.balance →
--     MOD(i*7919, 20000001)/100 (same 0..200000 range, 2 dp, deterministic);
--     orders_coalesce.updated_at is NULL when MOD(i*37, 100) < 35 (exactly 35%,
--     scattered — MySQL's RAND(i) < 0.35 gives ~35%). Which rows are NULL differs.
--   * MySQL escapes: 'line1\nline2' → 'line1' || CHR(10) || 'line2';
--     'quote \"and\", comma' → 'quote "and", comma'.
--   * Non-ASCII literal 'unicode: 日本語 🚀' is built with UNISTR so it survives any
--     sqlplus client NLS_LANG.
--   * repeat('L', n) → RPAD for n <= 4000, TO_CLOB-concatenation beyond (CLOB).
--   * ELT/IF/CONCAT/HEX/% → DECODE/CASE/||/TO_CHAR(i,'FMXXXXXXXX')/MOD.
--     DATE_SUB(d, INTERVAL -x UNIT) → d + NUMTODSINTERVAL(x, 'UNIT').
--   * ANALYZE TABLE → DBMS_STATS.GATHER_TABLE_STATS.
--   * Unquoted identifiers: Oracle stores every table/column name UPPER-case.

SET DEFINE OFF
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DROP VIEW IF EXISTS orders_sparse_for_export;
DROP TABLE IF EXISTS content_items PURGE;
DROP TABLE IF EXISTS page_views PURGE;
DROP TABLE IF EXISTS events PURGE;
DROP TABLE IF EXISTS orders PURGE;
DROP TABLE IF EXISTS users CASCADE CONSTRAINTS PURGE;
DROP TABLE IF EXISTS orders_sparse PURGE;
DROP TABLE IF EXISTS orders_coalesce PURGE;
DROP TABLE IF EXISTS rivet_type_matrix PURGE;
DROP TABLE IF EXISTS row_hash_probe PURGE;

CREATE TABLE users (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(200) NOT NULL,
    age NUMBER(10),
    balance NUMBER(12,2),
    is_active BOOLEAN DEFAULT TRUE,
    bio VARCHAR2(4000),
    created_at TIMESTAMP(0) DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(0) DEFAULT LOCALTIMESTAMP NOT NULL
);

CREATE TABLE orders (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER(10) NOT NULL,
    product VARCHAR2(200) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    notes VARCHAR2(4000),
    ordered_at TIMESTAMP(0) DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(0) DEFAULT LOCALTIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE events (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER(10) NOT NULL,
    event_type VARCHAR2(50) NOT NULL,
    payload JSON,
    ip_address VARCHAR2(45),
    created_at TIMESTAMP(0) DEFAULT LOCALTIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_orders_updated_at ON orders(updated_at);
CREATE INDEX idx_events_created_at ON events(created_at);
CREATE INDEX idx_events_user_id ON events(user_id);

-- Wide table, NO index on created_at -- intentionally degraded
CREATE TABLE page_views (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    session_id VARCHAR2(36) NOT NULL,
    user_id NUMBER(10),
    url VARCHAR2(4000) NOT NULL,
    referrer VARCHAR2(4000),
    user_agent VARCHAR2(4000),
    ip_address VARCHAR2(45),
    country_code CHAR(2),
    region VARCHAR2(100),
    city VARCHAR2(100),
    device_type VARCHAR2(20),
    browser VARCHAR2(50),
    os VARCHAR2(50),
    screen_width NUMBER(10),
    screen_height NUMBER(10),
    viewport_width NUMBER(10),
    viewport_height NUMBER(10),
    page_load_ms NUMBER(10),
    dom_ready_ms NUMBER(10),
    time_on_page_ms NUMBER(10),
    scroll_depth_pct NUMBER(5),
    click_count NUMBER(5),
    is_bounce BOOLEAN DEFAULT FALSE NOT NULL,
    utm_source VARCHAR2(100),
    utm_medium VARCHAR2(100),
    utm_campaign VARCHAR2(200),
    utm_term VARCHAR2(200),
    utm_content VARCHAR2(200),
    custom_props JSON,
    created_at TIMESTAMP(0) DEFAULT LOCALTIMESTAMP NOT NULL
);

-- Heavy-text table, NO index on created_at -- worst case for memory
CREATE TABLE content_items (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(4000) NOT NULL,
    body CLOB NOT NULL,
    raw_html CLOB NOT NULL,
    metadata JSON,
    tags VARCHAR2(4000),
    author_name VARCHAR2(100) NOT NULL,
    author_email VARCHAR2(200) NOT NULL,
    source_url VARCHAR2(4000),
    category VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'draft' NOT NULL,
    priority NUMBER(10) DEFAULT 0 NOT NULL,
    view_count NUMBER(10) DEFAULT 0 NOT NULL,
    comment_count NUMBER(10) DEFAULT 0 NOT NULL,
    word_count NUMBER(10) DEFAULT 0 NOT NULL,
    language CHAR(2) DEFAULT 'en' NOT NULL,
    published_at TIMESTAMP(0),
    updated_at TIMESTAMP(0) DEFAULT LOCALTIMESTAMP NOT NULL,
    created_at TIMESTAMP(0) DEFAULT LOCALTIMESTAMP NOT NULL,
    extra_data JSON
);

-- Sparse BIGINT ids — chunked mode demo (window functions)
CREATE TABLE orders_sparse (
    id NUMBER(19) PRIMARY KEY,
    payload VARCHAR2(4000) NOT NULL
);

CREATE OR REPLACE VIEW orders_sparse_for_export AS
SELECT
    id,
    payload,
    ROW_NUMBER() OVER (ORDER BY id) AS chunk_rownum
FROM orders_sparse;

-- Composite cursor fixture (ADR-0007): some rows have NULL in the primary
-- `updated_at` column, forcing `COALESCE(updated_at, created_at)` progression.
CREATE TABLE orders_coalesce (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    product VARCHAR2(200) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    updated_at TIMESTAMP(0) NULL,                                   -- primary
    created_at TIMESTAMP(0) DEFAULT LOCALTIMESTAMP NOT NULL          -- fallback, never NULL
);

CREATE INDEX idx_orders_coalesce_updated_at ON orders_coalesce(updated_at);
CREATE INDEX idx_orders_coalesce_created_at ON orders_coalesce(created_at);

-- ─── Type-matrix: the MySQL canonical type matrix, in Oracle's nearest types ──
-- Same columns and rows as seeds/common/mysql.sql; see the header for each
-- substitution (unsigned → NUMBER+CHECK, TIME → INTERVAL DAY TO SECOND,
-- ENUM/SET/YEAR/BIT → constrained VARCHAR2/NUMBER, BINARY → RAW pre-padded).
CREATE TABLE rivet_type_matrix (
    id NUMBER(19) PRIMARY KEY,
    c_tinyint NUMBER(3) NOT NULL,
    c_tinyint_u NUMBER(3) NOT NULL CHECK (c_tinyint_u BETWEEN 0 AND 255),
    c_bool NUMBER(1) NOT NULL CHECK (c_bool IN (0, 1)),
    c_boolean BOOLEAN NOT NULL,
    c_smallint NUMBER(5) NOT NULL,
    c_smallint_u NUMBER(5) NOT NULL CHECK (c_smallint_u BETWEEN 0 AND 65535),
    c_int NUMBER(10) NOT NULL,
    c_int_u NUMBER(10) NOT NULL CHECK (c_int_u BETWEEN 0 AND 4294967295),
    c_bigint NUMBER(19) NOT NULL,
    c_bigint_u NUMBER(20) NOT NULL CHECK (c_bigint_u BETWEEN 0 AND 18446744073709551615),
    amount NUMBER(18, 2) NULL,
    fee NUMBER(20, 6) NULL,
    price NUMBER(10, 2) NULL,
    c_float BINARY_FLOAT NOT NULL,
    c_double BINARY_DOUBLE NOT NULL,
    c_date DATE NOT NULL,
    c_time INTERVAL DAY(0) TO SECOND(6) NOT NULL,
    created_at_dt TIMESTAMP(6) NOT NULL,
    created_at_ts TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL,
    label VARCHAR2(200) NOT NULL,
    c_char CHAR(10) NOT NULL,
    c_text VARCHAR2(4000) NOT NULL,
    c_varchar VARCHAR2(50) NOT NULL,
    long_text CLOB NOT NULL,
    medium_text CLOB NOT NULL,
    raw_bytes RAW(4) NOT NULL,
    var_bytes RAW(8) NOT NULL,
    blob_bytes BLOB NOT NULL,
    "UID" VARCHAR2(36) NOT NULL,
    extras JSON NOT NULL,
    enum_col VARCHAR2(1) NOT NULL CHECK (enum_col IN ('a', 'b', 'c')),
    set_col VARCHAR2(5) NOT NULL CHECK (set_col IN ('x', 'y', 'z', 'x,y', 'x,z', 'y,z', 'x,y,z')),
    year_col NUMBER(4) NOT NULL CHECK (year_col BETWEEN 1901 AND 2155),
    c_bit1 NUMBER(1) NOT NULL CHECK (c_bit1 IN (0, 1)),
    c_bit8 NUMBER(3) NOT NULL CHECK (c_bit8 BETWEEN 0 AND 255),
    note_nullable VARCHAR2(500),
    note_all_null VARCHAR2(500)
);

INSERT INTO rivet_type_matrix (
    id, c_tinyint, c_tinyint_u, c_bool, c_boolean,
    c_smallint, c_smallint_u, c_int, c_int_u, c_bigint, c_bigint_u,
    amount, fee, price, c_float, c_double, c_date, c_time,
    created_at_dt, created_at_ts, label, c_char, c_text, c_varchar,
    long_text, medium_text,
    raw_bytes, var_bytes, blob_bytes, "UID", extras,
    enum_col, set_col, year_col, c_bit1, c_bit8,
    note_nullable, note_all_null
) VALUES
  (1, 5, 255, 1, TRUE,
      1, 65535, 2, 4294967295, 9223372036854775807, 18446744073709551615,
      0.10, 0.000001, 1234.56, 1.5f, 2.25d,
      DATE '2035-08-07', INTERVAL '0 09:08:07.987654' DAY(0) TO SECOND(6),
      TIMESTAMP '2035-08-07 09:08:07.987654', TIMESTAMP '2035-08-07 09:08:07.987654 +00:00',
      'payments-like', 'char-a    ', 'text row 1', 'varchar-a',
      TO_CLOB(RPAD('L', 4000, 'L')) || RPAD('L', 1000, 'L'), RPAD('M', 3000, 'M'),
      HEXTORAW('00ff0123'), HEXTORAW('0102030405060708'), TO_BLOB(HEXTORAW('cafebabe')),
      'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380011',
      JSON_OBJECT('tier' VALUE 'gold', 'n' VALUE 1),
      'b', 'x,y', 2024, 1, 255,
      'line1' || CHR(10) || 'line2', NULL),
  (2, -5, 0, 0, FALSE,
      -1, 0, -2, 0, -9223372036854775808, 9223372036854775808,
      0.20, 0.000002, -99.99, -1.5f, -2.25d,
      DATE '2019-02-03', INTERVAL '0 03:07:06.554433' DAY(0) TO SECOND(6),
      TIMESTAMP '2019-02-03 03:07:06.554433', TIMESTAMP '2019-02-03 03:07:06.554433 +00:00',
      'payments-like', 'char-b    ', 'text row 2', 'varchar-b',
      TO_CLOB(RPAD('L', 4000, 'L')), RPAD('M', 2000, 'M'),
      HEXTORAW('deadbeef'), HEXTORAW('aabbccddeeff0011'), TO_BLOB(HEXTORAW('00')),
      'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380022',
      JSON_ARRAY('a', 'b'),
      'a', 'x', 2000, 0, 1,
      'quote "and", comma', NULL),
  (3, 127, 200, 1, TRUE,
      32767, 60000, 2147483647, 4000000000, 0, 1,
      999999999999.99, 10.123456, 0.01, 0.0f, 1e100d,
      DATE '2020-01-15', INTERVAL '0 00:00:00.000001' DAY(0) TO SECOND(6),
      TIMESTAMP '2020-01-15 00:00:00.000001', TIMESTAMP '2020-01-15 00:00:00.000001 +00:00',
      'payments-like', 'char-c    ', 'text row 3', 'varchar-c',
      TO_CLOB(RPAD('L', 3000, 'L')), RPAD('M', 1000, 'M'),
      HEXTORAW('cafe0000'), HEXTORAW('ff'), TO_BLOB(HEXTORAW('dead')),
      'c0eebc99-9c0b-4ef8-bb6d-6bb9bd380033',
      JSON_OBJECT('big' VALUE TRUE),
      'c', 'y,z', 1999, 1, 255,
      NULL, NULL),
  (4, -128, 1, 0, FALSE,
      -32768, 1, -2147483648, 1, 42, 0,
      -100.05, -0.123456, 9999999.99, 3.14f, -1e50d,
      DATE '2021-06-30', INTERVAL '0 12:59:59.999999' DAY(0) TO SECOND(6),
      TIMESTAMP '2021-06-30 12:59:59.999999', TIMESTAMP '2021-06-30 12:59:59.999999 +00:00',
      'payments-like', 'char-d    ', 'text row 4', 'varchar-d',
      TO_CLOB(RPAD('L', 2000, 'L')), RPAD('M', 500, 'M'),
      HEXTORAW('00000000'), HEXTORAW('00'), EMPTY_BLOB(),
      'd0eebc99-9c0b-4ef8-bb6d-6bb9bd380044',
      JSON_OBJECT(),
      'a', 'z', 1970, 0, 0,
      'unicode: ' || UNISTR('\65E5\672C\8A9E \D83D\DE80'), NULL);

-- ============================================================================
-- DATA FILL — fast-profile reproduction of the Rust seeder (fast.rs, MySQL path).
-- CONNECT BY LEVEL row generator = the MySQL recursive CTE; id = i explicitly.
-- Row counts dogfood-sized; edit each `LEVEL <= N` to scale.
-- ============================================================================

INSERT INTO users (id, name, email, age, balance, is_active, bio, created_at, updated_at)
SELECT i, 'User ' || i, 'user' || i || '@example.com', 18 + MOD(i, 48), ROUND(MOD(i * 7919, 20000001) / 100, 2),
       MOD(i, 10) <> 0, CASE WHEN MOD(i, 3) = 0 THEN 'seed bio ' || i END,
       TIMESTAMP '2023-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 730), 'HOUR'),
       TIMESTAMP '2023-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 910), 'HOUR')
FROM (SELECT LEVEL i FROM dual CONNECT BY LEVEL <= 150000);

INSERT INTO orders (id, user_id, product, quantity, price, status, notes, ordered_at, updated_at)
SELECT i, LEAST(1 + FLOOR((i - 1) / 10), 2000),
       DECODE(MOD(i, 10), 0, 'MacBook Pro', 1, 'Dell XPS', 2, 'ThinkPad', 3, 'Surface', 4, 'Ergonomic Chair',
                          5, 'Standing Desk', 6, 'Monitor Arm', 7, 'USB-C Hub', 8, 'Mechanical Keyboard', 'Magic Mouse'),
       1 + MOD(i, 10), ROUND(5 + MOD(i, 4995), 2),
       DECODE(MOD(i, 4), 0, 'pending', 1, 'shipped', 2, 'delivered', 'cancelled'),
       CASE WHEN MOD(i, 3) = 0 THEN 'note ' || i END,
       TIMESTAMP '2023-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 730), 'MINUTE'),
       TIMESTAMP '2023-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 760), 'MINUTE')
FROM (SELECT LEVEL i FROM dual CONNECT BY LEVEL <= 150000);

INSERT INTO events (id, user_id, event_type, payload, ip_address, created_at)
SELECT i, LEAST(1 + FLOOR((i - 1) / 25), 2000),
       DECODE(MOD(i, 10), 0, 'login', 1, 'logout', 2, 'page_view', 3, 'purchase', 4, 'signup',
                          5, 'settings_change', 6, 'password_reset', 7, 'search', 8, 'export', 'api_call'),
       JSON_OBJECT('seed' VALUE TRUE, 'i' VALUE i), '10.' || MOD(i, 255) || '.' || MOD(i * 7, 255) || '.1',
       TIMESTAMP '2023-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 730), 'MINUTE')
FROM (SELECT LEVEL i FROM dual CONNECT BY LEVEL <= 150000);

INSERT INTO page_views (id,session_id,user_id,url,referrer,user_agent,ip_address,country_code,region,city,device_type,browser,os,screen_width,screen_height,viewport_width,viewport_height,page_load_ms,dom_ready_ms,time_on_page_ms,scroll_depth_pct,click_count,is_bounce,utm_source,utm_medium,utm_campaign,utm_term,utm_content,custom_props,created_at)
SELECT i, LPAD(TO_CHAR(i, 'FMXXXXXXXX'), 32, '0'), CASE WHEN MOD(i, 3) = 0 THEN 1 + MOD(i, 2000) END, '/page/' || MOD(i, 26),
       CASE WHEN MOD(i, 4) = 0 THEN 'https://google.com' END, 'Mozilla/5.0 seed', '192.168.' || MOD(i, 255) || '.' || (MOD(i * 3, 254) + 1),
       DECODE(MOD(i, 5), 0, 'US', 1, 'GB', 2, 'DE', 3, 'FR', 'CA'), 'Region ' || MOD(i, 10), 'City ' || MOD(i, 20),
       DECODE(MOD(i, 3), 0, 'desktop', 1, 'mobile', 'tablet'), DECODE(MOD(i, 3), 0, 'chrome', 1, 'firefox', 'safari'), DECODE(MOD(i, 3), 0, 'macOS', 1, 'Windows', 'Linux'),
       1280 + MOD(i, 2560), 720 + MOD(i, 1440), 800 + MOD(i, 1200), 600 + MOD(i, 900),
       100 + MOD(i, 5000), 50 + MOD(i, 2500), 500 + MOD(i, 60000), MOD(i, 101), MOD(i, 51), MOD(i, 3) = 0,
       CASE WHEN MOD(i, 4) = 0 THEN 'google' END, CASE WHEN MOD(i, 4) = 0 THEN 'cpc' END, CASE WHEN MOD(i, 8) = 0 THEN 'spring_sale' END, NULL, NULL,
       CASE WHEN MOD(i, 5) = 0 THEN JSON_OBJECT('seed' VALUE TRUE) END, TIMESTAMP '2023-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 730), 'MINUTE')
FROM (SELECT LEVEL i FROM dual CONNECT BY LEVEL <= 150000);

INSERT INTO content_items (id,title,body,raw_html,metadata,tags,author_name,author_email,source_url,category,status,priority,view_count,comment_count,word_count,language,published_at,updated_at,created_at,extra_data)
SELECT i, 'Seed title ' || i, TO_CLOB(RPAD('lorem ipsum ', 240, 'lorem ipsum ')), TO_CLOB('<p>' || RPAD('lorem ipsum ', 240, 'lorem ipsum ') || '</p>'),
       JSON_OBJECT('seed' VALUE TRUE, 'i' VALUE i), 'rust,postgres,data', 'Author ' || MOD(i, 1000), 'author' || MOD(i, 1000) || '@example.com',
       'https://blog.example.com/posts/' || i, DECODE(MOD(i, 3), 0, 'engineering', 1, 'product', 'tutorial'), DECODE(MOD(i, 3), 0, 'draft', 1, 'review', 'published'),
       MOD(i, 5), MOD(i, 100000), MOD(i, 500), 200, 'en',
       CASE WHEN MOD(i, 3) <> 0 THEN TIMESTAMP '2024-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 365), 'DAY') END,
       TIMESTAMP '2024-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 400), 'DAY'), TIMESTAMP '2023-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 730), 'DAY'),
       JSON_OBJECT('revisions' VALUE 1)
FROM (SELECT LEVEL i FROM dual CONNECT BY LEVEL <= 150000);

INSERT INTO orders_sparse (id, payload) VALUES (1,'s0'),(2000001,'s1'),(4000001,'s2');

INSERT INTO orders_coalesce (id, product, quantity, price, updated_at, created_at)
SELECT i, DECODE(MOD(i, 5), 0, 'MacBook Pro', 1, 'Dell XPS', 2, 'ThinkPad', 3, 'Surface', 'Ergonomic Chair'), 1 + MOD(i, 10), ROUND(5 + MOD(i, 4995), 2),
       CASE WHEN MOD(i * 37, 100) < 35 THEN NULL ELSE TIMESTAMP '2025-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 365), 'DAY') END,
       TIMESTAMP '2024-01-01 00:00:00' + NUMTODSINTERVAL(MOD(i, 365), 'DAY')
FROM (SELECT LEVEL i FROM dual CONNECT BY LEVEL <= 150000);

-- Move every identity past the explicitly-seeded ids (MySQL's AUTO_INCREMENT does
-- this implicitly), so a test that inserts without an id gets max(id)+1.
ALTER TABLE users MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE orders MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE events MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE page_views MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE content_items MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE orders_coalesce MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE);

COMMIT;

-- Refresh table stats so `rivet init` sees the TRUE row counts right after a fresh
-- seed (else every 150K table scaffolds `mode: full` instead of keyset).
BEGIN
    FOR t IN (SELECT column_value AS name FROM TABLE(sys.odcivarchar2list(
        'USERS', 'ORDERS', 'EVENTS', 'PAGE_VIEWS', 'CONTENT_ITEMS',
        'ORDERS_SPARSE', 'ORDERS_COALESCE', 'RIVET_TYPE_MATRIX'))) LOOP
        DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => t.name);
    END LOOP;
END;
/

-- === GARBAGE PROFILE ===
-- Obfuscated GARBAGE-profile fixture — identical to dev/garbage/oracle.sql (see its
-- header for the per-table deviations; they are the same rules as above).

DROP TABLE IF EXISTS ext_bigint_pk_dual_ts PURGE;
CREATE TABLE ext_bigint_pk_dual_ts (
    id NUMBER(19) PRIMARY KEY,
    payload VARCHAR2(4000) NOT NULL,
    created_at TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(0) WITH LOCAL TIME ZONE NULL
);
INSERT INTO ext_bigint_pk_dual_ts (id, payload, updated_at)
SELECT n, 'row' || n, SYSTIMESTAMP - NUMTODSINTERVAL(n, 'MINUTE')
FROM (SELECT LEVEL n FROM dual CONNECT BY LEVEL <= 150000);

DROP TABLE IF EXISTS ext_int_pk_dual_ts PURGE;
CREATE TABLE ext_int_pk_dual_ts (
    id NUMBER(10) PRIMARY KEY,
    payload VARCHAR2(4000) NOT NULL,
    created_at TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(0) WITH LOCAL TIME ZONE NULL
);
INSERT INTO ext_int_pk_dual_ts (id, payload, updated_at)
SELECT n, 'row' || n, SYSTIMESTAMP - NUMTODSINTERVAL(n, 'MINUTE')
FROM (SELECT LEVEL n FROM dual CONNECT BY LEVEL <= 150000);

-- The field DB CASTs id AS UNSIGNED — a BIGINT UNSIGNED PK with ids PAST
-- i64::MAX. Keyset must read the high-water key past i64 (#bc512a3), or it
-- loses/duplicates the tail. Oracle: NUMBER(20) + CHECK stands in for UNSIGNED.
DROP TABLE IF EXISTS ext_bigint_unsigned_pk PURGE;
CREATE TABLE ext_bigint_unsigned_pk (
    id NUMBER(20) PRIMARY KEY CHECK (id BETWEEN 0 AND 18446744073709551615),
    payload NUMBER(10) NOT NULL
);
INSERT INTO ext_bigint_unsigned_pk (id, payload)
SELECT n, n FROM (SELECT LEVEL n FROM dual CONNECT BY LEVEL <= 150000);
-- Three ids past i64::MAX (9223372036854775807); u64::MAX = 18446744073709551615.
INSERT INTO ext_bigint_unsigned_pk (id, payload) VALUES
    (18446744073709551613, 100), (18446744073709551614, 101), (18446744073709551615, 102);

-- Sparse key: id span vastly exceeds the row count (the sparse-guard shape).
DROP TABLE IF EXISTS ext_sparse_key PURGE;
CREATE TABLE ext_sparse_key (id NUMBER(19) PRIMARY KEY, payload NUMBER(10) NOT NULL);
INSERT INTO ext_sparse_key (id, payload)
SELECT 1 + n * 1000000, n FROM (SELECT LEVEL - 1 n FROM dual CONNECT BY LEVEL <= 150000);

-- Scale-0 DECIMAL PK (Oracle/ERP shape) — an explicit range chunk_column on it
-- must LOUDLY bail (#103); `chunk_by_key: dkey` (keyset) IS accepted.
DROP TABLE IF EXISTS ext_decimal_key PURGE;
CREATE TABLE ext_decimal_key (dkey NUMBER(15,0) PRIMARY KEY, payload VARCHAR2(4000) NOT NULL);
INSERT INTO ext_decimal_key (dkey, payload)
SELECT n, 'row' || n FROM (SELECT LEVEL n FROM dual CONNECT BY LEVEL <= 150000);

-- Keyless, cursorless → full-mode fallback.
DROP TABLE IF EXISTS ext_no_pk_no_ts PURGE;
CREATE TABLE ext_no_pk_no_ts (label VARCHAR2(4000) NOT NULL, amount NUMBER(10) NOT NULL);
INSERT INTO ext_no_pk_no_ts (label, amount)
SELECT 'label' || n, MOD(n, 100) FROM (SELECT LEVEL n FROM dual CONNECT BY LEVEL <= 150000);

-- ── The MESSY reality (distilled from a real stuck run's state DB) ───────────
-- HISTORY/VERSION table: NO `id`, keyed by a non-PK integer `ref_id`. The planner
-- range-CHUNKS on ref_id. Non-unique index on ref_id, no PK.
DROP TABLE IF EXISTS ext_ref_id_history PURGE;
CREATE TABLE ext_ref_id_history (
    ref_id NUMBER(19) NOT NULL,
    version NUMBER(10) NOT NULL,
    field VARCHAR2(4000),
    field_cur VARCHAR2(4000),
    sign NUMBER(5) DEFAULT 1 NOT NULL,
    status VARCHAR2(4000),
    -- money as DECIMAL(11,4) VALUE columns — the DOMINANT field profile.
    cart NUMBER(11,4),
    earning NUMBER(11,4),
    subtotal NUMBER(11,4),
    total NUMBER(11,4),
    amount_cur VARCHAR2(4000),
    user_cur CHAR(3),
    purchase_type VARCHAR2(4000),
    created_at TIMESTAMP(0) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP(0) WITH LOCAL TIME ZONE NULL
);
CREATE INDEX ix_ref_id ON ext_ref_id_history (ref_id);
INSERT INTO ext_ref_id_history (ref_id, version, field, field_cur, sign, status, cart, earning, subtotal, total, amount_cur, user_cur, purchase_type, created_at, updated_at)
SELECT MOD(n, 400) + 1, TRUNC(n / 400) + 1, 'f' || n, 'EUR', CASE WHEN MOD(n, 2) = 0 THEN 1 ELSE -1 END,
       DECODE(MOD(n, 3), 0, 'pending', 1, 'done', 'void'),
       (MOD(n, 900000) + 1) / 100.0, (MOD(n, 500000) + 1) / 100.0, (MOD(n, 300000) + 1) / 100.0, (MOD(n, 1200000) + 1) / 100.0,
       'USD', DECODE(MOD(n, 3), 0, 'EUR', 1, 'USD', 'PLN'), DECODE(MOD(n, 2), 0, 'a', 'b'),
       SYSTIMESTAMP - NUMTODSINTERVAL(n, 'MINUTE'), SYSTIMESTAMP - NUMTODSINTERVAL(n, 'SECOND')
FROM (SELECT LEVEL n FROM dual CONNECT BY LEVEL <= 150000);

-- Keyed by `order_id` (NOT `id`): a unique key makes it keyset-able on a non-`id`
-- key. Wide-ish string columns (md5/currency/subid).
DROP TABLE IF EXISTS ext_order_keyed PURGE;
CREATE TABLE ext_order_keyed (
    order_id NUMBER(19) NOT NULL,
    md5 CHAR(32) NOT NULL,
    currency CHAR(3) NOT NULL,
    status VARCHAR2(4000) NOT NULL,
    subid VARCHAR2(4000),
    advcampaign_id NUMBER(10),
    CONSTRAINT ux_order_id UNIQUE (order_id)
);
INSERT INTO ext_order_keyed (order_id, md5, currency, status, subid, advcampaign_id)
SELECT n, LOWER(RAWTOHEX(STANDARD_HASH(TO_CHAR(n), 'MD5'))),
       DECODE(MOD(n, 3), 0, 'EUR', 1, 'USD', 'PLN'), DECODE(MOD(n, 2), 0, 'approved', 'declined'),
       'sub' || MOD(n, 50), MOD(n, 900) + 100
FROM (SELECT LEVEL n FROM dual CONNECT BY LEVEL <= 150000);

-- HEAP: no PK, no index → full mode only.
DROP TABLE IF EXISTS ext_heap_no_key PURGE;
CREATE TABLE ext_heap_no_key (payload VARCHAR2(4000) NOT NULL, n NUMBER(10) NOT NULL);
INSERT INTO ext_heap_no_key (payload, n)
SELECT RPAD('x', 20 + MOD(s, 50), 'x'), s FROM (SELECT LEVEL s FROM dual CONNECT BY LEVEL <= 150000);

-- NAME-TRAP: a column literally named `id` that is NOT a PK and NOT indexed.
-- init picks keyset ONLY for a catalog single-column PRIMARY KEY (never by the
-- name `id`), so this must NOT scaffold `chunk_by_key: id`.
DROP TABLE IF EXISTS ext_unindexed_id PURGE;
CREATE TABLE ext_unindexed_id (id NUMBER(19) NOT NULL, label VARCHAR2(4000) NOT NULL, amount NUMBER(10) NOT NULL);
INSERT INTO ext_unindexed_id (id, label, amount)
SELECT n, 'row' || n, MOD(n, 100) FROM (SELECT LEVEL n FROM dual CONNECT BY LEVEL <= 150000);

-- ── row_hash injectivity probe ───────────────────────────────────────────────
-- See seeds/common/postgres.sql for the full rationale. Rows 1 and 2 are the
-- pair that render id v1 could not tell apart: with fields joined by a bare \x1f
-- and no length, ('a'||US,'b') and ('a',US||'b') build the SAME bytes. Rows 3
-- and 4 are absence versus a PRESENT value of length zero — BUT Oracle stores ''
-- as NULL, so here row 4 is (NULL,'x') exactly like row 3 (see header).
CREATE TABLE row_hash_probe (
    id NUMBER(10) PRIMARY KEY,
    a  VARCHAR2(4000),
    b  VARCHAR2(4000)
);

INSERT INTO row_hash_probe (id, a, b) VALUES
    (1, 'a' || CHR(31), 'b'),
    (2, 'a',            CHR(31) || 'b'),
    (3, NULL,           'x'),
    (4, '',             'x');

COMMIT;
