//! Backward-compatibility tests for plan / summary artifacts.
//!
//! These tests freeze artifacts generated by an older binary and re-parse
//! them with the **current** deserializer. If a future PR removes a field,
//! renames it, or changes a serde rename, the frozen fixture stops parsing
//! and the test fails — before users with committed plan.json artifacts
//! hit a confusing error.
//!
//! The fixtures live under `tests/fixtures/artifacts_legacy/`. Each was
//! captured from a real `rivet plan` / `rivet run` against the fixture
//! tables in docker-compose at the version named in the filename.
//!
//! Why JSON-shape, not the Rust type: `plan::artifact::PlanArtifact` is
//! `pub(crate)` and intentionally not part of any external API. We validate
//! the **wire format** an existing-on-disk plan.json must satisfy — that's
//! what end users actually depend on, and it's what `rivet apply` reads.
//!
//! When the schema MUST change incompatibly: document the migration in
//! CHANGELOG, update the fixture in the same PR, and ideally provide a
//! one-shot migration tool.

use serde_json::Value;

const LEGACY_FULL: &str = include_str!("fixtures/artifacts_legacy/v0_7_5_plan_full.json");
const LEGACY_INCR: &str = include_str!("fixtures/artifacts_legacy/v0_7_5_plan_incremental.json");
const LEGACY_CHUNKED: &str = include_str!("fixtures/artifacts_legacy/v0_7_5_plan_chunked.json");
const LEGACY_SUMMARY: &str = include_str!("fixtures/artifacts_legacy/v0_7_5_summary.json");

fn parse(label: &str, body: &str) -> Value {
    serde_json::from_str(body).unwrap_or_else(|e| panic!("{label} not valid JSON: {e}"))
}

fn require_field(label: &str, v: &Value, field: &str) {
    assert!(
        v.get(field).is_some(),
        "{label}: missing field '{field}'. \
         If this rename is intentional, ship a migration AND update the fixture."
    );
}

#[test]
fn v0_7_5_plan_full_top_level_fields_present() {
    let v = parse("v0.7.5 plan full", LEGACY_FULL);
    for field in [
        "rivet_version",
        "plan_id",
        "created_at",
        "expires_at",
        "export_name",
        "strategy",
        "plan_fingerprint",
        "resolved_plan",
    ] {
        require_field("v0.7.5 plan full", &v, field);
    }
    assert_eq!(v["rivet_version"].as_str(), Some("0.7.5"));
    assert_eq!(v["strategy"].as_str(), Some("full"));
    assert_eq!(v["export_name"].as_str(), Some("pa_audit"));
}

#[test]
fn v0_7_5_plan_resolved_plan_subfields_present() {
    let v = parse("v0.7.5 plan full", LEGACY_FULL);
    let rp = v
        .get("resolved_plan")
        .expect("resolved_plan must be present");
    for field in [
        "export_name",
        "base_query",
        "format",
        "compression",
        "destination",
        "tuning",
        "meta_columns",
    ] {
        require_field("v0.7.5 resolved_plan", rp, field);
    }
}

#[test]
fn v0_7_5_plan_destination_subfields_present() {
    let v = parse("v0.7.5 plan full", LEGACY_FULL);
    let dest = &v["resolved_plan"]["destination"];
    // Pin the union: every destination-related field that an apply may read
    // must be present and `null` if not used. A change that re-flattens the
    // destination (e.g. moves S3 fields under `destination.s3`) breaks here.
    for field in [
        "type",
        "bucket",
        "prefix",
        "path",
        "region",
        "endpoint",
        "credentials_file",
        "access_key_env",
        "secret_key_env",
        "session_token_env",
        "aws_profile",
        "account_name",
        "account_key_env",
        "sas_token_env",
        "allow_anonymous",
    ] {
        require_field("v0.7.5 destination", dest, field);
    }
}

#[test]
fn v0_7_5_plan_incremental_strategy_label_matches() {
    let v = parse("v0.7.5 plan incremental", LEGACY_INCR);
    assert_eq!(v["strategy"].as_str(), Some("incremental"));
    // Incremental-specific fields should be reachable somewhere on the
    // resolved plan. Be liberal — accept either nested or flat layouts.
    let rp = &v["resolved_plan"];
    let dump = serde_json::to_string(rp).unwrap();
    assert!(
        dump.contains("cursor_column") || dump.contains("Incremental"),
        "incremental plan must carry cursor info — got: {dump}"
    );
}

#[test]
fn v0_7_5_plan_chunked_strategy_label_matches() {
    let v = parse("v0.7.5 plan chunked", LEGACY_CHUNKED);
    assert_eq!(v["strategy"].as_str(), Some("chunked"));
    let rp = &v["resolved_plan"];
    let dump = serde_json::to_string(rp).unwrap();
    assert!(
        dump.contains("chunk_size") || dump.contains("Chunked"),
        "chunked plan must carry chunk info — got: {dump}"
    );
}

#[test]
fn v0_7_5_summary_top_level_fields_present() {
    // A v0.7.5 summary.json is what `notifications.slack` and the trust
    // artifacts machinery read. The shape is operator-visible and must
    // stay stable across patches.
    let v = parse("v0.7.5 summary", LEGACY_SUMMARY);
    // Don't pin every field (summary has many optional metrics) — just
    // the spine that downstream consumers definitely rely on.
    for field in ["run_id", "export_name", "status"] {
        require_field("v0.7.5 summary", &v, field);
    }
}
