//! Artifact compatibility gate — staff class #4: OLD artifacts × NEW binary.
//!
//! The formats a running deployment leaves on disk — checkpoint files, run
//! manifests, parquet parts — must stay readable by every future binary, or
//! the first post-upgrade run silently re-anchors / fails validation. These
//! fixtures were generated by v0.16.x and are COMMITTED; this test parses
//! them with the CURRENT code. When a format evolves, the new reader must
//! keep accepting these bytes (add a new fixture generation alongside — never
//! replace the old one).

use rivet::manifest::RunManifest;

const DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/compat/v0.16");

#[test]
fn v016_checkpoint_files_are_still_valid_json_for_every_engine() {
    // DOCUMENTS the on-disk shape; it does not verify rivet can still RESUME
    // from these files — that needs the real loader and lives beside it, in
    // `src/source/cdc/validate.rs::v016_checkpoint_compat`. Kept because a
    // fixture that stops being valid JSON is worth catching early and cheaply.
    for (engine, file, key) in [
        ("mysql", "mysql_cdc.ckpt", "file"),
        ("postgres", "pg_cdc.ckpt", "lsn"),
        ("mssql", "mssql_cdc.ckpt", "lsn"),
    ] {
        let body = std::fs::read_to_string(format!("{DIR}/{file}")).unwrap();
        let v: serde_json::Value =
            serde_json::from_str(&body).unwrap_or_else(|e| panic!("{engine} ckpt: {e}"));
        assert!(
            v.get(key).is_some(),
            "{engine}: the v0.16 checkpoint key '{key}' must stay readable"
        );
    }
}

#[test]
fn v016_cdc_manifest_deserializes_and_keeps_its_contract_fields() {
    let body = std::fs::read_to_string(format!("{DIR}/cdc_manifest.json")).unwrap();
    let m: RunManifest = serde_json::from_str(&body)
        .expect("a v0.16 CDC manifest must deserialize with the current schema");
    assert_eq!(m.manifest_version, 1, "manifest_version 1 stays supported");
    assert_eq!(m.export_name, "compat_gen");
    assert_eq!(m.parts.len(), 1, "the committed run has one part");
    assert_eq!(m.row_count, 3);
}

#[test]
fn v016_cdc_parquet_part_bytes_still_readable_by_current_arrow() {
    // Pins the ARROW/PARQUET dependency's ability to read 0.16 bytes — not
    // rivet's CDC reader, which never runs here. A rivet-side meta-column
    // change is invisible to this test by construction.
    let f = std::fs::File::open(format!("{DIR}/cdc_part.parquet")).unwrap();
    let r = parquet::arrow::arrow_reader::ParquetRecordBatchReaderBuilder::try_new(f)
        .unwrap()
        .build()
        .unwrap();
    let mut rows = 0;
    for b in r {
        let b = b.unwrap();
        assert!(b.schema().index_of("__op").is_ok(), "meta columns present");
        assert!(b.schema().index_of("__pos").is_ok());
        rows += b.num_rows();
    }
    assert_eq!(rows, 3, "the committed part holds its 3 rows");
}
