"""Known reds: gate failures acknowledged with a reason and an expiry, so a red gate on main
is red ONLY for recorded reasons. A matching failure is reported as KNOWN, not blocking; an
expired entry blocks again; an entry that no failure matched in a FULL run blocks too (fixed —
remove it). Matched by a substring of the failure message, one entry per acknowledged defect.

An open product defect is pinned by a live_suite cell that asserts the CORRECT behaviour and so
fails until the fix lands: the cell is named `open_defect_*` and marked `live+gate-only` (CI has no
such ledger and would only go red), and its entry here is `<module>::<fn> — <its first panic line>`,
the defect's own symptom. The fix PR deletes the entry; the cell stays as the regression guard.
"""

from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass


@dataclass(frozen=True)
class KnownRed:
    match: str
    reason: str
    expires: str  # YYYY-MM-DD


_EXPIRES = "2026-10-31"
_PROGRESS_KEY = ("stored progress has no single owner key (export, normalised source, stream, mode); the work item is the "
                 "progress key, PROGRESS-KEY-DESIGN.md")


def _open(cell: str, symptom: str, reason: str) -> KnownRed:
    """The entry of one `open_defect_*` live cell: its test path and the first line of its panic."""
    return KnownRed(f"{cell} — {symptom}", reason, _EXPIRES)


KNOWN_RED: tuple[KnownRed, ...] = (
    _open("live_reconcile_repair::open_defect_repair_after_a_chunk_column_edit_lists_each_row_once",
          "P-21: a repair under an edited chunk_column left the manifest listing 39 rows over 39 distinct ids for 40 source ids",
          f"P-21: reconcile and repair do not compare the stored plan fingerprint, so a repair re-reads the stored windows on the new column and supersedes the parts; {_PROGRESS_KEY}"),
    _open("audit_state::open_defect_state_reset_during_an_incremental_read_keeps_the_manifest_honest",
          "P-23: a `state reset` accepted during an incremental read left a manifest with no cursor_low over a delta: its parts hold ids [11, 12, 13] of 1..=13",
          "P-23: the manifest's cursor_low is a second state read after the export, and `state reset` is accepted beside a live run; the work item is the run lease (#461 holds it for chunk_checkpoint runs only; whether every run holds it is an open decision)"),
    _open("live_plan_apply::open_defect_a_sealed_plan_keeps_the_date_placeholder",
          "P-26: the sealed plan holds no `{date}` placeholder",
          "P-26: `rivet plan` resolves `{date}` into the artifact, so an apply after UTC midnight writes under the planning date; the work item is the planner-and-paths PR (TRIAGE PR-M), pending the ADR-0005 decision on what a sealed plan freezes"),
    _open("live_destination_parity::open_defect_a_relative_destination_path_does_not_follow_the_working_directory",
          "P-27: one config with a relative destination.path delivered ids [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] under the first working directory and [11, 12, 13] under the second",
          "P-27: a relative `destination.path` resolves against the working directory while the cursor lives beside the config; the work item is the planner-and-paths PR (TRIAGE PR-M): anchor it to the config directory"),
    _open("chunking_stand::open_defect_a_float_chunk_column_under_query_keeps_its_fractional_keys_postgres",
          "rig oracle: COUNT(*): source 43, delivered 40",
          "A `double precision` chunk_column under `query:` is sliced by integer BETWEEN windows and drops the fractional keys with exit 0 (a WARN only); found beside P-24/P-25 (#458), no work item yet: refuse it or slice half-open"),
    _open("audit_cli_dispatch::open_defect_apply_pool_writes_only_the_export_on_stdout",
          "oracle error: dev/release_oracle/rig_oracle.py grade-stdout exited",
          "`rivet apply --pool` prints its pool lines on stdout, into the bytes of a `destination: stdout` export; found beside P-14/P-28 (#463), no work item yet: the lines belong on stderr Since #463 the rig oracle grades a stdout export first and its `grade-stdout` raises on the foreign lines instead of giving a verdict, so that is the first line the cell shows"),
    _open("live_partition_by::open_defect_partition_by_exports_a_declared_numeric_column",
          "`partition_by` over a table with a NUMERIC(10,2) column failed under `rivet run`: precision/scale unavailable",
          "`partition_by` reads each partition through a subquery, which loses the catalog's NUMERIC(p,s), so the export is refused although the unpartitioned one runs; found beside P-14 (#463), no work item yet"),
    _open("live_operator_contract::open_defect_a_second_concurrent_full_run_does_not_double_the_prefix_postgres",
          'rig oracle: COUNT(*): source 200, delivered 400',
          'Sweep 4: two concurrent `full` runs of one export both exit 0 and the prefix holds every key twice; only checkpointed runs hold the run lease'),
    _open("live_operator_contract::open_defect_a_second_concurrent_full_run_does_not_double_the_prefix_mysql",
          'rig oracle: COUNT(*): source 200, delivered 400',
          'Sweep 4: two concurrent `full` runs of one export both exit 0 and the prefix holds every key twice; only checkpointed runs hold the run lease'),
    _open("live_operator_contract::open_defect_a_second_concurrent_full_run_does_not_double_the_prefix_mssql",
          'rig oracle: COUNT(*): source 200, delivered 400',
          'Sweep 4: two concurrent `full` runs of one export both exit 0 and the prefix holds every key twice; only checkpointed runs hold the run lease'),
    _open("live_operator_contract::open_defect_a_second_concurrent_full_run_does_not_double_the_prefix_oracle",
          'rig oracle: COUNT(*): source 200, delivered 400',
          'Sweep 4: two concurrent `full` runs of one export both exit 0 and the prefix holds every key twice; only checkpointed runs hold the run lease'),
    _open("live_operator_contract::open_defect_a_second_run_beside_a_live_checkpointed_run_is_refused_by_code_postgres",
          'refusal contract: the invocation ended with no RIVET_* code (exit 1), expected [RIVET_STATE_RUN_IN_PROGRESS] (exit 5)',
          'Sweep 11: a second run beside a live checkpointed run exits 1 with no code; `state reset-chunks` in the same situation gives RIVET_STATE_RUN_IN_PROGRESS (5)'),
    _open("live_operator_contract::open_defect_a_second_run_beside_a_live_checkpointed_run_is_refused_by_code_mysql",
          'refusal contract: the invocation ended with no RIVET_* code (exit 1), expected [RIVET_STATE_RUN_IN_PROGRESS] (exit 5)',
          'Sweep 11: a second run beside a live checkpointed run exits 1 with no code; `state reset-chunks` in the same situation gives RIVET_STATE_RUN_IN_PROGRESS (5)'),
    _open("live_operator_contract::open_defect_a_second_run_beside_a_live_checkpointed_run_is_refused_by_code_mssql",
          'refusal contract: the invocation ended with no RIVET_* code (exit 1), expected [RIVET_STATE_RUN_IN_PROGRESS] (exit 5)',
          'Sweep 11: a second run beside a live checkpointed run exits 1 with no code; `state reset-chunks` in the same situation gives RIVET_STATE_RUN_IN_PROGRESS (5)'),
    _open("live_operator_contract::open_defect_removing_page_size_runs_after_the_heterogeneous_id_refusal_mongo",
          'refuse-then-remedy: remedy `Remove `page_size`` ended with [RIVET_STATE_INTERRUPTED_RUN_OWNER_MISMATCH] (exit 5), expected exit 0 and the source delivered',
          'Sweep 14: the refused resume has already claimed the cursor row, so the remedy the refusal names (a full scan without `page_size`) is refused as an interrupted run of another mode; exit 0 on v0.31.0'),
    _open("live_operator_contract::open_defect_a_second_concurrent_full_run_does_not_double_the_prefix_mongo",
          "rig oracle: COUNT(*): source 300000, delivered 600000",
          "Sweep 4: a second `full` run beside a live one is not refused; both exit 0 and the prefix holds every key twice"),
    _open("live_operator_contract::open_defect_a_second_run_beside_a_live_checkpointed_run_is_refused_by_code_oracle",
          "refusal contract: the invocation ended with no RIVET_* code (exit 1), expected [RIVET_STATE_RUN_IN_PROGRESS] (exit 5)",
          "Sweep 11: a second run beside a live checkpointed run exits 1 with no code; `state reset-chunks` in the same situation gives RIVET_STATE_RUN_IN_PROGRESS (5)"),
    _open("live_operator_contract::open_defect_a_second_run_beside_a_live_resumable_run_is_refused_by_code_mongo",
          "refusal contract: the invocation ended with no RIVET_* code (exit 1), expected [RIVET_STATE_RUN_IN_PROGRESS] (exit 5)",
          "Sweep 11: a second run beside a live checkpointed run exits 1 with no code; `state reset-chunks` in the same situation gives RIVET_STATE_RUN_IN_PROGRESS (5)"),
    _open("live_operator_contract::open_defect_init_cdc_writes_the_capture_instance_the_catalog_holds_mssql",
          "assertion `left == right` failed: `rivet init --mode cdc` wrote a capture instance cdc.change_tables does not hold for dbo.oc_initc_",
          "Sweep 19: `rivet init --mode cdc` on SQL Server derives `capture_instance: dbo_<table>` and does not read `cdc.change_tables`, so the run refuses an instance the catalog does not know"),
    _open("live_operator_contract::open_defect_range_chunking_takes_a_number_19_key_oracle",
          "range chunking refused an Oracle NUMBER(19) integer key (exit Some(1))",
          "2026-10-06 finding: range chunking refuses an Oracle `NUMBER(19)` primary key (scale 0) as not integer-family, while it takes `NUMBER(18)`"),
    KnownRed('upgrade[oracle/cdc-load]: cycle1/load: prev exit 1: Error: config has no top-level `load:` block',
             "Oracle CDC does not load yet (ADR-0037; the Oracle GA work). The previous release's `rivet init --mode cdc` writes no `load:` block, and this cell still drives the previous release through `load`, which refuses. `upgrade[oracle/cdc-load/init=this]` grades what the scaffold does promise (the baseline Parquet equals the source). The cycle stays unsupported until Oracle CDC loads",
             "2026-10-31"),
    KnownRed('upgrade[oracle/cdc-load/tz=Asia/Tokyo]: cycle1/load: prev exit 1: Error: config has no top-level `load:` block',
             "Oracle CDC does not load yet (ADR-0037; the Oracle GA work). The previous release's `rivet init --mode cdc` writes no `load:` block, and this cell still drives the previous release through `load`, which refuses. `upgrade[oracle/cdc-load/init=this]` grades what the scaffold does promise (the baseline Parquet equals the source). The cycle stays unsupported until Oracle CDC loads",
             "2026-10-31"),
    KnownRed('sentinels[rivet_sent_ts9/full]: SUCCEEDED WITH A CHANGED VALUE: `V` differs',
             "Oracle TIMESTAMP(9) is delivered at microseconds today: docs/type-capability-matrix.yaml's oracle TIMESTAMP(9) row is a known_defect (exact native is Timestamp(ns), ADR-0038 CP1, Oracle engine step), so the 1 ns sentinel lands truncated",
             "2026-10-31"),
    KnownRed('sentinels[rivet_sent_ts9/keyset]: SUCCEEDED WITH A CHANGED VALUE: `V` differs',
             "Oracle TIMESTAMP(9) is delivered at microseconds today: docs/type-capability-matrix.yaml's oracle TIMESTAMP(9) row is a known_defect (exact native is Timestamp(ns), ADR-0038 CP1, Oracle engine step), so the 1 ns sentinel lands truncated",
             "2026-10-31"),
    _open("live_sabotage::open_defect_validate_fails_on_a_marker_without_a_manifest_postgres",
          "`rivet validate`: report 1 ended with exit 0, expected exit 3 (integrity)",
          "exit 0 over an unverifiable prefix: `rivet validate` reports `status: legacy_run` and exits 0 when manifest.json is gone although `_SUCCESS` and the parts are there (the local sibling of RESULTS 5, a missing bucket); no work item yet: a marker without a manifest is a failed verification"),
    _open("live_sabotage::open_defect_validate_fails_on_a_marker_without_a_manifest_mysql",
          "`rivet validate`: report 1 ended with exit 0, expected exit 3 (integrity)",
          "exit 0 over an unverifiable prefix: `rivet validate` reports `status: legacy_run` and exits 0 when manifest.json is gone although `_SUCCESS` and the parts are there (the local sibling of RESULTS 5, a missing bucket); no work item yet: a marker without a manifest is a failed verification"),
    _open("live_sabotage::open_defect_validate_fails_on_a_marker_without_a_manifest_mssql",
          "`rivet validate`: report 1 ended with exit 0, expected exit 3 (integrity)",
          "exit 0 over an unverifiable prefix: `rivet validate` reports `status: legacy_run` and exits 0 when manifest.json is gone although `_SUCCESS` and the parts are there (the local sibling of RESULTS 5, a missing bucket); no work item yet: a marker without a manifest is a failed verification"),
    _open("live_sabotage::open_defect_validate_fails_on_a_marker_without_a_manifest_mongo",
          "`rivet validate`: report 1 ended with exit 0, expected exit 3 (integrity)",
          "exit 0 over an unverifiable prefix: `rivet validate` reports `status: legacy_run` and exits 0 when manifest.json is gone although `_SUCCESS` and the parts are there (the local sibling of RESULTS 5, a missing bucket); no work item yet: a marker without a manifest is a failed verification"),
    _open("live_sabotage::open_defect_a_resume_over_a_task_marked_completed_delivers_or_refuses_postgres",
          "rig oracle: COUNT(*): source 40, delivered 35",
          "exit 0 over wrong data: a pending chunk task marked `completed` (no file, no rows) is skipped by the resume, which writes a success manifest and `_SUCCESS` five rows short, and `validate` passes; observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_resume_over_a_task_marked_completed_delivers_or_refuses_mysql",
          "rig oracle: COUNT(*): source 40, delivered 35",
          "exit 0 over wrong data: a pending chunk task marked `completed` (no file, no rows) is skipped by the resume, which writes a success manifest and `_SUCCESS` five rows short, and `validate` passes; observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_resume_over_a_task_marked_completed_delivers_or_refuses_mssql",
          "rig oracle: COUNT(*): source 40, delivered 35",
          "exit 0 over wrong data: a pending chunk task marked `completed` (no file, no rows) is skipped by the resume, which writes a success manifest and `_SUCCESS` five rows short, and `validate` passes; observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_resume_over_edited_task_bounds_delivers_or_refuses_postgres",
          "rig oracle: COUNT(*): source 40, delivered 38",
          "exit 0 over wrong data: a pending chunk task with a lowered upper bound leaves a hole between two tasks, the resume writes a success manifest two rows short, and `validate` passes; observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_resume_over_edited_task_bounds_delivers_or_refuses_mysql",
          "rig oracle: COUNT(*): source 40, delivered 38",
          "exit 0 over wrong data: a pending chunk task with a lowered upper bound leaves a hole between two tasks, the resume writes a success manifest two rows short, and `validate` passes; observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_resume_over_edited_task_bounds_delivers_or_refuses_mssql",
          "rig oracle: COUNT(*): source 40, delivered 38",
          "exit 0 over wrong data: a pending chunk task with a lowered upper bound leaves a hole between two tasks, the resume writes a success manifest two rows short, and `validate` passes; observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_an_edited_plan_fingerprint_delivers_or_is_refused_by_code_and_led_out_postgres",
          "after the sabotage `rivet run` refused with no RIVET_* code (exit 1): a refusal is expected by its registry code",
          "a refusal with no code: a resume whose stored plan fingerprint differs is refused with exit 1 and no RIVET_* code (the text does name `rivet state reset-chunks`, which leads out), while a mode change under the same unfinished run is RIVET_STATE_INTERRUPTED_RUN_OWNER_MISMATCH (exit 5); CLI sweep pattern C, no work item yet: a registry code for it"),
    _open("live_sabotage::open_defect_an_edited_plan_fingerprint_delivers_or_is_refused_by_code_and_led_out_mysql",
          "after the sabotage `rivet run` refused with no RIVET_* code (exit 1): a refusal is expected by its registry code",
          "a refusal with no code: a resume whose stored plan fingerprint differs is refused with exit 1 and no RIVET_* code (the text does name `rivet state reset-chunks`, which leads out), while a mode change under the same unfinished run is RIVET_STATE_INTERRUPTED_RUN_OWNER_MISMATCH (exit 5); CLI sweep pattern C, no work item yet: a registry code for it"),
    _open("live_sabotage::open_defect_an_edited_plan_fingerprint_delivers_or_is_refused_by_code_and_led_out_mssql",
          "after the sabotage `rivet run` refused with no RIVET_* code (exit 1): a refusal is expected by its registry code",
          "a refusal with no code: a resume whose stored plan fingerprint differs is refused with exit 1 and no RIVET_* code (the text does name `rivet state reset-chunks`, which leads out), while a mode change under the same unfinished run is RIVET_STATE_INTERRUPTED_RUN_OWNER_MISMATCH (exit 5); CLI sweep pattern C, no work item yet: a registry code for it"),
    _open("live_sabotage::open_defect_a_resume_over_a_truncated_committed_part_delivers_or_refuses_postgres",
          "oracle error: dev/release_oracle/rig_oracle.py grade exited",
          "exit 0 over wrong data: the resume names a truncated committed part in its success manifest (a later `rivet validate` fails with RIVET_VERIFY_PART_SIZE_MISMATCH), and the rig oracle cannot read the part, so the cell's first line is the oracle's error; observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_resume_over_a_truncated_committed_part_delivers_or_refuses_mysql",
          "oracle error: dev/release_oracle/rig_oracle.py grade exited",
          "exit 0 over wrong data: the resume names a truncated committed part in its success manifest (a later `rivet validate` fails with RIVET_VERIFY_PART_SIZE_MISMATCH), and the rig oracle cannot read the part, so the cell's first line is the oracle's error; observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_resume_over_a_truncated_committed_part_delivers_or_refuses_mssql",
          "oracle error: dev/release_oracle/rig_oracle.py grade exited",
          "exit 0 over wrong data: the resume names a truncated committed part in its success manifest (a later `rivet validate` fails with RIVET_VERIFY_PART_SIZE_MISMATCH), and the rig oracle cannot read the part, so the cell's first line is the oracle's error; observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_resume_over_a_replaced_committed_part_delivers_or_refuses_postgres",
          "rig oracle: COUNT(DISTINCT `id`): source 40, delivered 35",
          "exit 0 over wrong data: a committed part whose bytes were replaced by its same-sized sibling is named in the resume's success manifest, and `validate` passes (its report counts the parts as size-only verified); observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_resume_over_a_replaced_committed_part_delivers_or_refuses_mysql",
          "rig oracle: COUNT(DISTINCT `id`): source 40, delivered 35",
          "exit 0 over wrong data: a committed part whose bytes were replaced by its same-sized sibling is named in the resume's success manifest, and `validate` passes (its report counts the parts as size-only verified); observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_resume_over_a_replaced_committed_part_delivers_or_refuses_mssql",
          "rig oracle: COUNT(DISTINCT `id`): source 40, delivered 35",
          "exit 0 over wrong data: a committed part whose bytes were replaced by its same-sized sibling is named in the resume's success manifest, and `validate` passes (its report counts the parts as size-only verified); observed, not read from the code: a plain re-run that resumes the checkpoint takes the chunk_task rows as stored and reuses a committed part that exists (a deleted part is re-exported, a truncated or replaced one is not); the `--resume` reconciliation (src/pipeline/chunked/resume_m8.rs) was not walked; no work item yet: refuse a checkpoint whose tasks do not tile the planned range, and size-check a committed part before reusing it"),
    _open("live_sabotage::open_defect_a_cursor_moved_forward_delivers_or_refuses_postgres",
          "rig oracle: COUNT(*): source 43, delivered 41",
          "exit 0 over wrong data: a stored cursor moved past rows the export never delivered is continued from, although the destination's own manifests end below it (`cursor_high` of the last success manifest); no work item yet, owner decision: compare the stored cursor with the destination's last `cursor_high` and refuse a cursor above it, or declare the state row trusted"),
    _open("live_sabotage::open_defect_a_cursor_moved_forward_delivers_or_refuses_mysql",
          "rig oracle: COUNT(*): source 43, delivered 41",
          "exit 0 over wrong data: a stored cursor moved past rows the export never delivered is continued from, although the destination's own manifests end below it (`cursor_high` of the last success manifest); no work item yet, owner decision: compare the stored cursor with the destination's last `cursor_high` and refuse a cursor above it, or declare the state row trusted"),
    _open("live_sabotage::open_defect_a_cursor_moved_forward_delivers_or_refuses_mssql",
          "rig oracle: COUNT(*): source 43, delivered 41",
          "exit 0 over wrong data: a stored cursor moved past rows the export never delivered is continued from, although the destination's own manifests end below it (`cursor_high` of the last success manifest); no work item yet, owner decision: compare the stored cursor with the destination's last `cursor_high` and refuse a cursor above it, or declare the state row trusted"),
    _open("live_sabotage::open_defect_a_cursor_of_another_type_delivers_or_is_refused_by_code_and_led_out_postgres",
          "after the sabotage `rivet run` refused with no RIVET_* code (exit 1): a refusal is expected by its registry code",
          "a refusal nothing leads out of: a stored cursor the cursor column cannot be compared with fails every run with the driver's own conversion error (exit 1, no code, no remedy; `rivet state reset` does lead out); MySQL coerces the text to 0 and re-delivers the table; no work item yet: a coded refusal naming `rivet state reset`"),
    _open("live_sabotage::open_defect_a_cursor_of_another_type_delivers_or_is_refused_by_code_and_led_out_mssql",
          "after the sabotage `rivet run` refused with no RIVET_* code (exit 1): a refusal is expected by its registry code",
          "a refusal nothing leads out of: a stored cursor the cursor column cannot be compared with fails every run with the driver's own conversion error (exit 1, no code, no remedy; `rivet state reset` does lead out); MySQL coerces the text to 0 and re-delivers the table; no work item yet: a coded refusal naming `rivet state reset`"),
    _open("live_sabotage::open_defect_a_run_whose_azure_bucket_is_removed_delivers_or_fails_loudly_postgres",
          "the live run did not end within 180s of the action beside it",
          "other, a failure that takes minutes: with its Azure container removed mid-run the export retried a persistent 404 (`ContainerNotFound`, which its own summary calls persistent) 108 times and ended after 9 min 21 s with exit 1 and `chunk checkpoint incomplete` (by hand, Azurite); the s3 and gcs cells of the same row family end in seconds; no work item yet: a missing container is not retryable"),
    _open("live_sabotage::open_defect_a_run_out_of_file_descriptors_fails_loudly_and_the_next_delivers_postgres",
          "`rivet run` neither a delivery nor a loud failure: ended with exit 101",
          "other, a crash: a PostgreSQL export capped at 8 open files panics (`called Result::unwrap() on an Err value: Os { code: 24, .. \"Too many open files\" }` at postgres-0.19 src/config.rs:463, the client building its runtime) instead of failing with an `Error:` line; MySQL, SQL Server, Oracle and MongoDB fail loudly under the same cap on either state, and on a PostgreSQL state this export fails loudly too, at the state's connect, so the crash is the source client's and shows on a SQLite state; no work item yet"),
    _open("live_sabotage::open_defect_a_run_whose_state_volume_fills_up_delivers_or_fails_loudly_postgres",
          "rig oracle: unknown-status: export_metrics",
          "other, a stop nothing records: a run whose SQLite state volume fills up mid-export exits 1 and leaves its `export_metrics` and `run_status` rows `running` (it cannot write its own stop); no work item yet: decide whether the next run or `state runs` must reconcile them, or the oracle declares the leftover"),
    _open("live_sabotage::open_defect_a_run_whose_state_volume_fills_up_delivers_or_fails_loudly_mysql",
          "rig oracle: unknown-status: export_metrics",
          "other, a stop nothing records: a run whose SQLite state volume fills up mid-export exits 1 and leaves its `export_metrics` and `run_status` rows `running` (it cannot write its own stop); no work item yet: decide whether the next run or `state runs` must reconcile them, or the oracle declares the leftover"),
    _open("live_sabotage::open_defect_a_run_whose_state_volume_fills_up_delivers_or_fails_loudly_mssql",
          "rig oracle: unknown-status: export_metrics",
          "other, a stop nothing records: a run whose SQLite state volume fills up mid-export exits 1 and leaves its `export_metrics` and `run_status` rows `running` (it cannot write its own stop); no work item yet: decide whether the next run or `state runs` must reconcile them, or the oracle declares the leftover"),
    _open("live_sabotage::open_defect_a_run_whose_state_volume_fills_up_delivers_or_fails_loudly_oracle",
          "rig oracle: unknown-status: export_metrics",
          "other, a stop nothing records: a run whose SQLite state volume fills up mid-export exits 1 and leaves its `export_metrics` and `run_status` rows `running` (it cannot write its own stop); no work item yet: decide whether the next run or `state runs` must reconcile them, or the oracle declares the leftover"),
    _open("live_sabotage::open_defect_a_run_whose_state_volume_fills_up_delivers_or_fails_loudly_mongo",
          "rig oracle: success-marker: ",
          "exit 1 beside a success marker: a MongoDB export whose SQLite state volume fills up mid-export exits 1 after it wrote `_SUCCESS` and a success manifest, and leaves its journal rows `running`; no work item yet"),
    _open("live_sabotage::open_defect_a_second_range_run_beside_a_live_one_delivers_or_refuses_postgres",
          "rig oracle: COUNT(*): source 200, delivered 400",
          "exit 0 over wrong data: two concurrent runs of one range-chunked export both exit 0 and the destination declares every key twice (Sweep 4 on the chunked runners: only a checkpointed run holds the export's run lease); no work item beyond RESULTS 4: a run lease for every runner, or one manifest that names one run's parts"),
    _open("live_sabotage::open_defect_a_second_range_run_beside_a_live_one_delivers_or_refuses_mysql",
          "rig oracle: COUNT(*): source 200, delivered 400",
          "exit 0 over wrong data: two concurrent runs of one range-chunked export both exit 0 and the destination declares every key twice (Sweep 4 on the chunked runners: only a checkpointed run holds the export's run lease); no work item beyond RESULTS 4: a run lease for every runner, or one manifest that names one run's parts"),
    _open("live_sabotage::open_defect_a_second_range_run_beside_a_live_one_delivers_or_refuses_mssql",
          "rig oracle: COUNT(*): source 200, delivered 400",
          "exit 0 over wrong data: two concurrent runs of one range-chunked export both exit 0 and the destination declares every key twice (Sweep 4 on the chunked runners: only a checkpointed run holds the export's run lease); no work item beyond RESULTS 4: a run lease for every runner, or one manifest that names one run's parts"),
    _open("live_sabotage::open_defect_a_second_keyset_run_beside_a_live_one_delivers_or_refuses_postgres",
          "rig oracle: COUNT(*): source 200, delivered 400",
          "exit 0 over wrong data: two concurrent runs of one keyset export both exit 0 and the destination declares every key twice (Sweep 4 on the chunked runners: only a checkpointed run holds the export's run lease); no work item beyond RESULTS 4: a run lease for every runner, or one manifest that names one run's parts"),
    _open("live_sabotage::open_defect_a_second_keyset_run_beside_a_live_one_delivers_or_refuses_mysql",
          "rig oracle: COUNT(*): source 200, delivered 400",
          "exit 0 over wrong data: two concurrent runs of one keyset export both exit 0 and the destination declares every key twice (Sweep 4 on the chunked runners: only a checkpointed run holds the export's run lease); no work item beyond RESULTS 4: a run lease for every runner, or one manifest that names one run's parts"),
    _open("live_sabotage::open_defect_a_second_keyset_run_beside_a_live_one_delivers_or_refuses_mssql",
          "rig oracle: COUNT(*): source 200, delivered 400",
          "exit 0 over wrong data: two concurrent runs of one keyset export both exit 0 and the destination declares every key twice (Sweep 4 on the chunked runners: only a checkpointed run holds the export's run lease); no work item beyond RESULTS 4: a run lease for every runner, or one manifest that names one run's parts"),
    _open("live_sabotage::open_defect_a_second_keyset_checkpoint_run_beside_a_live_one_delivers_or_refuses_postgres",
          "the second run beside a live one refused with no RIVET_* code (exit 1): a refusal is expected by its registry code",
          "a refusal with no code: Sweep 11 on the keyset runner: a second run beside a live keyset-checkpoint run exits 1 with no RIVET_* code (the text does say to wait); `state reset` in the same situation is RIVET_STATE_RUN_IN_PROGRESS (5)"),
    _open("live_sabotage::open_defect_a_second_keyset_checkpoint_run_beside_a_live_one_delivers_or_refuses_mysql",
          "the second run beside a live one refused with no RIVET_* code (exit 1): a refusal is expected by its registry code",
          "a refusal with no code: Sweep 11 on the keyset runner: a second run beside a live keyset-checkpoint run exits 1 with no RIVET_* code (the text does say to wait); `state reset` in the same situation is RIVET_STATE_RUN_IN_PROGRESS (5)"),
    _open("live_sabotage::open_defect_a_second_keyset_checkpoint_run_beside_a_live_one_delivers_or_refuses_mssql",
          "the second run beside a live one refused with no RIVET_* code (exit 1): a refusal is expected by its registry code",
          "a refusal with no code: Sweep 11 on the keyset runner: a second run beside a live keyset-checkpoint run exits 1 with no RIVET_* code (the text does say to wait); `state reset` in the same situation is RIVET_STATE_RUN_IN_PROGRESS (5)"),
    _open("live_sabotage::open_defect_repair_beside_a_live_run_delivers_or_fails_loudly_postgres",
          "rig oracle: COUNT",
          "exit 0 over wrong data: `rivet repair --execute` does not take the export's run lease: beside a live checkpointed run it reads the pending chunks as mismatched and re-exports them while the run exports them too; both exit 0, and the run's success manifest is not the source (read on the stand: 40 rows declared for 200 keys; parts the run's own ledger does not hold; by hand on PostgreSQL 360 rows declared for 300 keys, where `rivet validate` then failed with exit 3); the first finding varies with the interleaving (`COUNT(*)` or `COUNTER:`), so the entry matches their common prefix; no work item yet: `repair` and `reconcile` claim the run lease like `state reset` (RIVET_STATE_RUN_IN_PROGRESS)"),
    _open("live_sabotage::open_defect_repair_beside_a_live_run_delivers_or_fails_loudly_mysql",
          "rig oracle: COUNT",
          "exit 0 over wrong data: `rivet repair --execute` does not take the export's run lease: beside a live checkpointed run it reads the pending chunks as mismatched and re-exports them while the run exports them too; both exit 0, and the run's success manifest is not the source (read on the stand: 40 rows declared for 200 keys; parts the run's own ledger does not hold; by hand on PostgreSQL 360 rows declared for 300 keys, where `rivet validate` then failed with exit 3); the first finding varies with the interleaving (`COUNT(*)` or `COUNTER:`), so the entry matches their common prefix; no work item yet: `repair` and `reconcile` claim the run lease like `state reset` (RIVET_STATE_RUN_IN_PROGRESS)"),
    _open("live_sabotage::open_defect_repair_beside_a_live_run_delivers_or_fails_loudly_mssql",
          "rig oracle: COUNT",
          "exit 0 over wrong data: `rivet repair --execute` does not take the export's run lease: beside a live checkpointed run it reads the pending chunks as mismatched and re-exports them while the run exports them too; both exit 0, and the run's success manifest is not the source (read on the stand: 40 rows declared for 200 keys; parts the run's own ledger does not hold; by hand on PostgreSQL 360 rows declared for 300 keys, where `rivet validate` then failed with exit 3); the first finding varies with the interleaving (`COUNT(*)` or `COUNTER:`), so the entry matches their common prefix; no work item yet: `repair` and `reconcile` claim the run lease like `state reset` (RIVET_STATE_RUN_IN_PROGRESS)"),
    _open("live_sabotage::open_defect_run_resume_over_a_task_marked_completed_delivers_or_refuses_postgres",
          "rig oracle: COUNT(*): source 40, delivered 35",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` skips a pending task marked `completed` and writes a success manifest and `_SUCCESS` five rows short; `rivet validate` passes afterwards; the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_a_task_marked_completed_delivers_or_refuses_mysql",
          "rig oracle: COUNT(*): source 40, delivered 35",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` skips a pending task marked `completed` and writes a success manifest and `_SUCCESS` five rows short; `rivet validate` passes afterwards; the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_a_task_marked_completed_delivers_or_refuses_mssql",
          "rig oracle: COUNT(*): source 40, delivered 35",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` skips a pending task marked `completed` and writes a success manifest and `_SUCCESS` five rows short; `rivet validate` passes afterwards; the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_edited_task_bounds_delivers_or_refuses_postgres",
          "rig oracle: COUNT(*): source 40, delivered 38",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` exports a task with a lowered upper bound as stored and writes a success manifest two rows short; `rivet validate` passes afterwards; the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_edited_task_bounds_delivers_or_refuses_mysql",
          "rig oracle: COUNT(*): source 40, delivered 38",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` exports a task with a lowered upper bound as stored and writes a success manifest two rows short; `rivet validate` passes afterwards; the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_edited_task_bounds_delivers_or_refuses_mssql",
          "rig oracle: COUNT(*): source 40, delivered 38",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` exports a task with a lowered upper bound as stored and writes a success manifest two rows short; `rivet validate` passes afterwards; the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_a_truncated_committed_part_delivers_or_refuses_postgres",
          "oracle error: dev/release_oracle/rig_oracle.py grade exited",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` names a truncated committed part in its success manifest, which the rig oracle cannot read, so the cell's first line is the oracle's error; `rivet validate` fails afterwards (exit 3); the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_a_truncated_committed_part_delivers_or_refuses_mysql",
          "oracle error: dev/release_oracle/rig_oracle.py grade exited",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` names a truncated committed part in its success manifest, which the rig oracle cannot read, so the cell's first line is the oracle's error; `rivet validate` fails afterwards (exit 3); the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_a_truncated_committed_part_delivers_or_refuses_mssql",
          "oracle error: dev/release_oracle/rig_oracle.py grade exited",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` names a truncated committed part in its success manifest, which the rig oracle cannot read, so the cell's first line is the oracle's error; `rivet validate` fails afterwards (exit 3); the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_a_replaced_committed_part_delivers_or_refuses_postgres",
          "rig oracle: COUNT(DISTINCT `id`): source 40, delivered 35",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` names a committed part whose bytes were replaced by its same-sized sibling in its success manifest; `rivet validate` passes afterwards; the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_a_replaced_committed_part_delivers_or_refuses_mysql",
          "rig oracle: COUNT(DISTINCT `id`): source 40, delivered 35",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` names a committed part whose bytes were replaced by its same-sized sibling in its success manifest; `rivet validate` passes afterwards; the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_sabotage::open_defect_run_resume_over_a_replaced_committed_part_delivers_or_refuses_mssql",
          "rig oracle: COUNT(DISTINCT `id`): source 40, delivered 35",
          "exit 0 over wrong data, under the explicit resume as under the plain re-run: `rivet run --resume` names a committed part whose bytes were replaced by its same-sized sibling in its success manifest; `rivet validate` passes afterwards; the default oracle grades the `--resume` run against the source, so this line is the oracle's; no work item yet: the same as the plain re-run row"),
    _open("live_mode_transition::open_defect_a_one_chunk_range_run_without_its_checkpoint_is_refused_as_its_own_mode_finish_the_run_postgres",
          "cycle 1: must name runs without the checkpoint that run was opened with",
          "2026-10-09: a `mode: chunked` export run as one pass because its table fits in one chunk names `full` as the owner of its progress, so beside an unfinished checkpoint run it is told `now runs as full` and to restore settings it still has; the fix is on branch fix/unfinished-chunk-run-refusal-on-a-small-table, postponed past the release gate"),
    _open("live_mode_transition::open_defect_a_one_chunk_range_run_without_its_checkpoint_is_refused_as_its_own_mode_finish_the_run_mysql",
          "cycle 1: must name runs without the checkpoint that run was opened with",
          "2026-10-09: a `mode: chunked` export run as one pass because its table fits in one chunk names `full` as the owner of its progress, so beside an unfinished checkpoint run it is told `now runs as full` and to restore settings it still has; the fix is on branch fix/unfinished-chunk-run-refusal-on-a-small-table, postponed past the release gate"),
    _open("live_mode_transition::open_defect_a_one_chunk_range_run_without_its_checkpoint_is_refused_as_its_own_mode_finish_the_run_mssql",
          "cycle 1: must name runs without the checkpoint that run was opened with",
          "2026-10-09: a `mode: chunked` export run as one pass because its table fits in one chunk names `full` as the owner of its progress, so beside an unfinished checkpoint run it is told `now runs as full` and to restore settings it still has; the fix is on branch fix/unfinished-chunk-run-refusal-on-a-small-table, postponed past the release gate"),
    _open("live_mode_transition::open_defect_a_one_chunk_range_run_without_its_checkpoint_is_refused_as_its_own_mode_finish_the_run_oracle",
          "cycle 1: must name runs without the checkpoint that run was opened with",
          "2026-10-09: a `mode: chunked` export run as one pass because its table fits in one chunk names `full` as the owner of its progress, so beside an unfinished checkpoint run it is told `now runs as full` and to restore settings it still has; the fix is on branch fix/unfinished-chunk-run-refusal-on-a-small-table, postponed past the release gate"),
    _open("live_mode_transition::open_defect_a_one_chunk_range_run_without_its_checkpoint_is_refused_as_its_own_mode_reset_postgres",
          "cycle 1: must name runs without the checkpoint that run was opened with",
          "2026-10-09: a `mode: chunked` export run as one pass because its table fits in one chunk names `full` as the owner of its progress, so beside an unfinished checkpoint run it is told `now runs as full` and to restore settings it still has; the fix is on branch fix/unfinished-chunk-run-refusal-on-a-small-table, postponed past the release gate"),
    _open("live_mode_transition::open_defect_a_one_chunk_range_run_without_its_checkpoint_is_refused_as_its_own_mode_reset_mysql",
          "cycle 1: must name runs without the checkpoint that run was opened with",
          "2026-10-09: a `mode: chunked` export run as one pass because its table fits in one chunk names `full` as the owner of its progress, so beside an unfinished checkpoint run it is told `now runs as full` and to restore settings it still has; the fix is on branch fix/unfinished-chunk-run-refusal-on-a-small-table, postponed past the release gate"),
    _open("live_mode_transition::open_defect_a_one_chunk_range_run_without_its_checkpoint_is_refused_as_its_own_mode_reset_mssql",
          "cycle 1: must name runs without the checkpoint that run was opened with",
          "2026-10-09: a `mode: chunked` export run as one pass because its table fits in one chunk names `full` as the owner of its progress, so beside an unfinished checkpoint run it is told `now runs as full` and to restore settings it still has; the fix is on branch fix/unfinished-chunk-run-refusal-on-a-small-table, postponed past the release gate"),
    _open("live_mode_transition::open_defect_a_one_chunk_range_run_without_its_checkpoint_is_refused_as_its_own_mode_reset_oracle",
          "cycle 1: must name runs without the checkpoint that run was opened with",
          "2026-10-09: a `mode: chunked` export run as one pass because its table fits in one chunk names `full` as the owner of its progress, so beside an unfinished checkpoint run it is told `now runs as full` and to restore settings it still has; the fix is on branch fix/unfinished-chunk-run-refusal-on-a-small-table, postponed past the release gate"),
    _open("live_mode_transition::open_defect_a_one_chunk_auto_keyset_run_without_its_checkpoint_is_refused_as_its_own_mode_finish_the_run_mysql",
          "cycle 1: must name runs without the checkpoint that run was opened with",
          "2026-10-09: a `mode: chunked` export run as one pass because its table fits in one chunk names `full` as the owner of its progress, so beside an unfinished checkpoint run it is told `now runs as full` and to restore settings it still has; the fix is on branch fix/unfinished-chunk-run-refusal-on-a-small-table, postponed past the release gate"),
    _open("live_mode_transition::open_defect_a_one_chunk_auto_keyset_run_without_its_checkpoint_is_refused_as_its_own_mode_reset_mysql",
          "cycle 1: must name runs without the checkpoint that run was opened with",
          "2026-10-09: a `mode: chunked` export run as one pass because its table fits in one chunk names `full` as the owner of its progress, so beside an unfinished checkpoint run it is told `now runs as full` and to restore settings it still has; the fix is on branch fix/unfinished-chunk-run-refusal-on-a-small-table, postponed past the release gate"),
    _open("live_operator_contract::open_defect_a_decimal_chunk_column_is_refused_whatever_the_row_estimate_postgres",
          "the config refused over 10 rows (`is not an integer-family column`) ran over 3 rows: exit Some(0), 3 rows delivered",
          "2026-10-09: the planner's small-table escape runs before the shape validation, so a `mode: chunked` config it refuses once the row estimate exceeds chunk_size plans and runs as one pass below it; no work item yet: validate the shape before the escape"),
    _open("live_operator_contract::open_defect_a_decimal_chunk_column_is_refused_whatever_the_row_estimate_mysql",
          "the config refused over 10 rows (`is not an integer-family column`) ran over 3 rows: exit Some(0), 3 rows delivered",
          "2026-10-09: the planner's small-table escape runs before the shape validation, so a `mode: chunked` config it refuses once the row estimate exceeds chunk_size plans and runs as one pass below it; no work item yet: validate the shape before the escape"),
    _open("live_operator_contract::open_defect_a_decimal_chunk_column_is_refused_whatever_the_row_estimate_mssql",
          "the config refused over 10 rows (`is not an integer-family column`) ran over 3 rows: exit Some(0), 3 rows delivered",
          "2026-10-09: the planner's small-table escape runs before the shape validation, so a `mode: chunked` config it refuses once the row estimate exceeds chunk_size plans and runs as one pass below it; no work item yet: validate the shape before the escape"),
    _open("live_operator_contract::open_defect_a_decimal_chunk_column_is_refused_whatever_the_row_estimate_oracle",
          "the config refused over 10 rows (`is not an integer-family column`) ran over 3 rows: exit Some(0), 3 rows delivered",
          "2026-10-09: the planner's small-table escape runs before the shape validation, so a `mode: chunked` config it refuses once the row estimate exceeds chunk_size plans and runs as one pass below it; no work item yet: validate the shape before the escape"),
    _open("live_operator_contract::open_defect_a_keyless_table_is_refused_whatever_the_row_estimate_postgres",
          "the config refused over 10 rows (`chunked mode found no safe shape`) ran over 3 rows: exit Some(0), 3 rows delivered",
          "2026-10-09: the planner's small-table escape runs before the shape validation, so a `mode: chunked` config it refuses once the row estimate exceeds chunk_size plans and runs as one pass below it; no work item yet: validate the shape before the escape"),
    _open("live_operator_contract::open_defect_a_keyless_table_is_refused_whatever_the_row_estimate_mysql",
          "the config refused over 10 rows (`chunked mode found no safe shape`) ran over 3 rows: exit Some(0), 3 rows delivered",
          "2026-10-09: the planner's small-table escape runs before the shape validation, so a `mode: chunked` config it refuses once the row estimate exceeds chunk_size plans and runs as one pass below it; no work item yet: validate the shape before the escape"),
    _open("live_operator_contract::open_defect_a_keyless_table_is_refused_whatever_the_row_estimate_mssql",
          "the config refused over 10 rows (`chunked mode found no safe shape`) ran over 3 rows: exit Some(0), 3 rows delivered",
          "2026-10-09: the planner's small-table escape runs before the shape validation, so a `mode: chunked` config it refuses once the row estimate exceeds chunk_size plans and runs as one pass below it; no work item yet: validate the shape before the escape"),
    _open("live_operator_contract::open_defect_a_keyless_table_is_refused_whatever_the_row_estimate_oracle",
          "the config refused over 10 rows (`chunked mode found no safe shape`) ran over 3 rows: exit Some(0), 3 rows delivered",
          "2026-10-09: the planner's small-table escape runs before the shape validation, so a `mode: chunked` config it refuses once the row estimate exceeds chunk_size plans and runs as one pass below it; no work item yet: validate the shape before the escape"),
)


def match(msg: str, today: _dt.date | None = None) -> tuple[KnownRed | None, bool]:
    """The entry `msg` matches and whether it is still in date."""
    today = today or _dt.date.today()
    for k in KNOWN_RED:
        if k.match in msg:
            return k, today <= _dt.date.fromisoformat(k.expires)
    return None, False
