"""Known reds: gate failures acknowledged with a reason and an expiry, so a red gate on main
is red ONLY for recorded reasons. A matching failure is reported as KNOWN, not blocking; an
expired entry blocks again; an entry that no failure matched in a FULL run blocks too (fixed —
remove it). Matched by a substring of the failure message, one entry per acknowledged defect.

An open product defect is pinned by a live_suite cell that asserts the CORRECT behaviour and so
fails until the fix lands: the cell is named `open_defect_*` and marked `live+gate-only` (CI has no
such ledger and would only go red), and its entry here is `<module>::<fn> — <its first panic line>`,
the defect's own symptom. The fix PR deletes the entry; the cell stays as the regression guard.
"""

from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass


@dataclass(frozen=True)
class KnownRed:
    match: str
    reason: str
    expires: str  # YYYY-MM-DD


_EXPIRES = "2026-10-31"
_PROGRESS_KEY = ("stored progress has no single owner key (export, normalised source, stream, mode); the work item is the "
                 "progress key, PROGRESS-KEY-DESIGN.md")


def _open(cell: str, symptom: str, reason: str) -> KnownRed:
    """The entry of one `open_defect_*` live cell: its test path and the first line of its panic."""
    return KnownRed(f"{cell} — {symptom}", reason, _EXPIRES)


KNOWN_RED: tuple[KnownRed, ...] = (
    _open("live_mode_transition::open_defect_source_url_without_its_default_port_continues_postgres",
          "P-18: the source URL without its default port lost the cursor: the run delivered ids [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]",
          f"P-18: the source key is the URL as spelled, so dropping `:5432` starts a whole-table pass; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_source_url_without_its_default_port_continues_mysql",
          "P-18: the source URL without its default port lost the cursor: the run delivered ids [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]",
          f"P-18: the source key is the URL as spelled, so dropping the default port starts a whole-table pass; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_source_url_without_its_default_port_continues_mssql",
          "P-18: the source URL without its default port lost the cursor: the run delivered ids [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]",
          f"P-18: the source key is the URL as spelled, so dropping the default port starts a whole-table pass; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_source_url_without_its_default_port_continues_oracle",
          "P-18: the source URL without its default port lost the cursor: the run delivered ids [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]",
          f"P-18: the source key is the URL as spelled, so dropping the default port starts a whole-table pass; {_PROGRESS_KEY}"),
    _open("audit_state::open_defect_state_reset_keeps_the_cursor_of_another_source",
          "P-19: `state reset` under one config deleted the cursor of a same-named export of another source: its next run re-delivered the table (14 rows on disk for 7 source ids)",
          f"P-19: `state reset --export` deletes by export name alone; {_PROGRESS_KEY}"),
    _open("live_reconcile_repair::open_defect_repair_after_a_chunk_column_edit_lists_each_row_once",
          "P-21: a repair under an edited chunk_column left the manifest listing 39 rows over 39 distinct ids for 40 source ids",
          f"P-21: reconcile and repair do not compare the stored plan fingerprint, so a repair re-reads the stored windows on the new column and supersedes the parts; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_resumed_parallel_keyset_then_incremental_postgres",
          "P-22: a resumed parallel keyset run stored a cursor below its own maximum",
          f"P-22: the resume publishes the high-water of the ranges it re-ran, not of the run; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_resumed_parallel_keyset_then_incremental_mysql",
          "P-22: a resumed parallel keyset run stored a cursor below its own maximum",
          f"P-22: the resume publishes the high-water of the ranges it re-ran, not of the run; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_resumed_parallel_keyset_then_incremental_mssql",
          "P-22: a resumed parallel keyset run stored a cursor below its own maximum",
          f"P-22: the resume publishes the high-water of the ranges it re-ran, not of the run; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_resumed_parallel_keyset_then_incremental_oracle",
          "P-22: a resumed parallel keyset run stored a cursor below its own maximum",
          f"P-22: the resume publishes the high-water of the ranges it re-ran, not of the run; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_same_table_in_another_schema_is_another_stream_postgres",
          "the same table name in another schema inherited the cursor: the run delivered ids [] of 1..=7 with exit 0",
          f"Cursor identity, found verifying #456: the source key drops the URL query, so `search_path` moves the export to another schema under the stored cursor; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_incremental_query_filter_edited_postgres",
          "an edited query filter inherited the old filter's cursor: the run delivered ids [] of 1..=5 with exit 0",
          f"Cursor identity, found verifying #456: the stream is the outer FROM relation, so an edited `query:` filter keeps the stored cursor; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_incremental_query_filter_edited_mysql",
          "an edited query filter inherited the old filter's cursor: the run delivered ids [] of 1..=5 with exit 0",
          f"Cursor identity, found verifying #456: the stream is the outer FROM relation, so an edited `query:` filter keeps the stored cursor; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_incremental_query_filter_edited_mssql",
          "an edited query filter inherited the old filter's cursor: the run delivered ids [] of 1..=5 with exit 0",
          f"Cursor identity, found verifying #456: the stream is the outer FROM relation, so an edited `query:` filter keeps the stored cursor; {_PROGRESS_KEY}"),
    _open("live_mode_transition::open_defect_incremental_query_filter_edited_oracle",
          "an edited query filter inherited the old filter's cursor: the run delivered ids [] of 1..=5 with exit 0",
          f"Cursor identity, found verifying #456: the stream is the outer FROM relation, so an edited `query:` filter keeps the stored cursor; {_PROGRESS_KEY}"),
    _open("audit_state::open_defect_state_reset_during_an_incremental_read_keeps_the_manifest_honest",
          "P-23: a `state reset` accepted during an incremental read left a manifest with no cursor_low over a delta: its parts hold ids [11, 12, 13] of 1..=13",
          "P-23: the manifest's cursor_low is a second state read after the export, and `state reset` is accepted beside a live run; the work item is the run lease (#461 holds it for chunk_checkpoint runs only; whether every run holds it is an open decision)"),
    _open("live_plan_apply::open_defect_a_sealed_plan_keeps_the_date_placeholder",
          "P-26: the sealed plan holds no `{date}` placeholder",
          "P-26: `rivet plan` resolves `{date}` into the artifact, so an apply after UTC midnight writes under the planning date; the work item is the planner-and-paths PR (TRIAGE PR-M), pending the ADR-0005 decision on what a sealed plan freezes"),
    _open("live_destination_parity::open_defect_a_relative_destination_path_does_not_follow_the_working_directory",
          "P-27: one config with a relative destination.path delivered ids [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] under the first working directory and [11, 12, 13] under the second",
          "P-27: a relative `destination.path` resolves against the working directory while the cursor lives beside the config; the work item is the planner-and-paths PR (TRIAGE PR-M): anchor it to the config directory"),
    _open("chunking_stand::open_defect_a_float_chunk_column_under_query_keeps_its_fractional_keys_postgres",
          "rig oracle: COUNT(*): source 43, delivered 40",
          "A `double precision` chunk_column under `query:` is sliced by integer BETWEEN windows and drops the fractional keys with exit 0 (a WARN only); found beside P-24/P-25 (#458), no work item yet: refuse it or slice half-open"),
    _open("audit_cli_dispatch::open_defect_apply_pool_writes_only_the_export_on_stdout",
          "oracle error: dev/release_oracle/rig_oracle.py grade-stdout exited",
          "`rivet apply --pool` prints its pool lines on stdout, into the bytes of a `destination: stdout` export; found beside P-14/P-28 (#463), no work item yet: the lines belong on stderr Since #463 the rig oracle grades a stdout export first and its `grade-stdout` raises on the foreign lines instead of giving a verdict, so that is the first line the cell shows"),
    _open("live_partition_by::open_defect_partition_by_exports_a_declared_numeric_column",
          "`partition_by` over a table with a NUMERIC(10,2) column failed under `rivet run`: precision/scale unavailable",
          "`partition_by` reads each partition through a subquery, which loses the catalog's NUMERIC(p,s), so the export is refused although the unpartitioned one runs; found beside P-14 (#463), no work item yet"),
    _open("live_operator_contract::open_defect_a_stale_chunk_checkpoint_is_not_adopted_after_a_finished_run_postgres",
          "rig oracle: VALUES: 15 source row(s) not delivered, 15 delivered row(s) not in the source; differing column(s) ['v'] of ['id', 'v']",
          'Sweep 1: a chunk checkpoint left by a crashed run is resumed after a later run (checkpoint off) finished the export, so the parts written before the crash are declared again with exit 0'),
    _open("live_operator_contract::open_defect_a_stale_chunk_checkpoint_is_not_adopted_after_a_finished_run_mysql",
          "rig oracle: VALUES: 15 source row(s) not delivered, 15 delivered row(s) not in the source; differing column(s) ['v'] of ['id', 'v']",
          'Sweep 1: a chunk checkpoint left by a crashed run is resumed after a later run (checkpoint off) finished the export, so the parts written before the crash are declared again with exit 0'),
    _open("live_operator_contract::open_defect_a_stale_chunk_checkpoint_is_not_adopted_after_a_finished_run_mssql",
          "rig oracle: VALUES: 15 source row(s) not delivered, 15 delivered row(s) not in the source; differing column(s) ['v'] of ['id', 'v']",
          'Sweep 1: a chunk checkpoint left by a crashed run is resumed after a later run (checkpoint off) finished the export, so the parts written before the crash are declared again with exit 0'),
    _open("live_operator_contract::open_defect_run_validate_does_not_exit_0_over_a_failed_validation_postgres",
          '`run --validate` exited 0 with `validated: FAIL`',
          'Sweep 2: `run --validate` prints `validated: FAIL` and exits 0, where `rivet validate` on the same prefix exits 3'),
    _open("live_operator_contract::open_defect_run_validate_does_not_exit_0_over_a_failed_validation_mysql",
          '`run --validate` exited 0 with `validated: FAIL`',
          'Sweep 2: `run --validate` prints `validated: FAIL` and exits 0, where `rivet validate` on the same prefix exits 3'),
    _open("live_operator_contract::open_defect_run_validate_does_not_exit_0_over_a_failed_validation_mssql",
          '`run --validate` exited 0 with `validated: FAIL`',
          'Sweep 2: `run --validate` prints `validated: FAIL` and exits 0, where `rivet validate` on the same prefix exits 3'),
    _open("live_operator_contract::open_defect_run_validate_does_not_exit_0_over_a_failed_validation_oracle",
          '`run --validate` exited 0 with `validated: FAIL`',
          'Sweep 2: `run --validate` prints `validated: FAIL` and exits 0, where `rivet validate` on the same prefix exits 3'),
    _open("live_operator_contract::open_defect_a_run_that_cannot_store_its_cursor_does_not_exit_0_postgres",
          'rig oracle: COUNTER: export_metrics has no success row for this run',
          'Sweep 3: with a read-only state DB the cursor advance fails after the manifest is written and the run still exits 0, so every run re-delivers the delta'),
    _open("live_operator_contract::open_defect_a_run_that_cannot_store_its_cursor_does_not_exit_0_mysql",
          'rig oracle: COUNTER: export_metrics has no success row for this run',
          'Sweep 3: with a read-only state DB the cursor advance fails after the manifest is written and the run still exits 0, so every run re-delivers the delta'),
    _open("live_operator_contract::open_defect_a_run_that_cannot_store_its_cursor_does_not_exit_0_mssql",
          'rig oracle: COUNTER: export_metrics has no success row for this run',
          'Sweep 3: with a read-only state DB the cursor advance fails after the manifest is written and the run still exits 0, so every run re-delivers the delta'),
    _open("live_operator_contract::open_defect_a_run_that_cannot_store_its_cursor_does_not_exit_0_oracle",
          'rig oracle: COUNTER: export_metrics has no success row for this run',
          'Sweep 3: with a read-only state DB the cursor advance fails after the manifest is written and the run still exits 0, so every run re-delivers the delta'),
    _open("live_operator_contract::open_defect_a_second_concurrent_full_run_does_not_double_the_prefix_postgres",
          'rig oracle: COUNT(*): source 200, delivered 400',
          'Sweep 4: two concurrent `full` runs of one export both exit 0 and the prefix holds every key twice; only checkpointed runs hold the run lease'),
    _open("live_operator_contract::open_defect_a_second_concurrent_full_run_does_not_double_the_prefix_mysql",
          'rig oracle: COUNT(*): source 200, delivered 400',
          'Sweep 4: two concurrent `full` runs of one export both exit 0 and the prefix holds every key twice; only checkpointed runs hold the run lease'),
    _open("live_operator_contract::open_defect_a_second_concurrent_full_run_does_not_double_the_prefix_mssql",
          'rig oracle: COUNT(*): source 200, delivered 400',
          'Sweep 4: two concurrent `full` runs of one export both exit 0 and the prefix holds every key twice; only checkpointed runs hold the run lease'),
    _open("live_operator_contract::open_defect_a_second_concurrent_full_run_does_not_double_the_prefix_oracle",
          'rig oracle: COUNT(*): source 200, delivered 400',
          'Sweep 4: two concurrent `full` runs of one export both exit 0 and the prefix holds every key twice; only checkpointed runs hold the run lease'),
    _open("live_operator_contract::open_defect_a_run_that_never_connected_keeps_the_export_complete_postgres",
          'a run that never connected left `_SUCCESS` withdrawn and manifest.json `failed` over a complete export',
          'Sweep 8 (owner decision 2026-10-07): a run that fails before its first write still rewrites manifest.json to failed and deletes `_SUCCESS`; it must leave both alone'),
    _open("live_operator_contract::open_defect_a_run_that_never_connected_keeps_the_export_complete_mysql",
          'a run that never connected left `_SUCCESS` withdrawn and manifest.json `failed` over a complete export',
          'Sweep 8 (owner decision 2026-10-07): a run that fails before its first write still rewrites manifest.json to failed and deletes `_SUCCESS`; it must leave both alone'),
    _open("live_operator_contract::open_defect_a_run_that_never_connected_keeps_the_export_complete_mssql",
          'a run that never connected left `_SUCCESS` withdrawn and manifest.json `failed` over a complete export',
          'Sweep 8 (owner decision 2026-10-07): a run that fails before its first write still rewrites manifest.json to failed and deletes `_SUCCESS`; it must leave both alone'),
    _open("live_operator_contract::open_defect_a_run_that_never_connected_keeps_the_export_complete_oracle",
          'a run that never connected left `_SUCCESS` withdrawn and manifest.json `failed` over a complete export',
          'Sweep 8 (owner decision 2026-10-07): a run that fails before its first write still rewrites manifest.json to failed and deletes `_SUCCESS`; it must leave both alone'),
    _open("live_operator_contract::open_defect_resume_force_runs_over_a_complete_prefix_postgres",
          'refuse-then-remedy: remedy `Pass --force to override` ended with no RIVET_* code (exit 1), expected exit 0 and the source delivered',
          'Sweep 12: the `--resume refused` text and `--force --help` promise an override; `--resume --force` exits 1 `nothing to continue`'),
    _open("live_operator_contract::open_defect_resume_force_runs_over_a_complete_prefix_mysql",
          'refuse-then-remedy: remedy `Pass --force to override` ended with no RIVET_* code (exit 1), expected exit 0 and the source delivered',
          'Sweep 12: the `--resume refused` text and `--force --help` promise an override; `--resume --force` exits 1 `nothing to continue`'),
    _open("live_operator_contract::open_defect_resume_force_runs_over_a_complete_prefix_mssql",
          'refuse-then-remedy: remedy `Pass --force to override` ended with no RIVET_* code (exit 1), expected exit 0 and the source delivered',
          'Sweep 12: the `--resume refused` text and `--force --help` promise an override; `--resume --force` exits 1 `nothing to continue`'),
    _open("live_operator_contract::open_defect_a_second_run_beside_a_live_checkpointed_run_is_refused_by_code_postgres",
          'refusal contract: the invocation ended with no RIVET_* code (exit 1), expected [RIVET_STATE_RUN_IN_PROGRESS] (exit 5)',
          'Sweep 11: a second run beside a live checkpointed run exits 1 with no code; `state reset-chunks` in the same situation gives RIVET_STATE_RUN_IN_PROGRESS (5)'),
    _open("live_operator_contract::open_defect_a_second_run_beside_a_live_checkpointed_run_is_refused_by_code_mysql",
          'refusal contract: the invocation ended with no RIVET_* code (exit 1), expected [RIVET_STATE_RUN_IN_PROGRESS] (exit 5)',
          'Sweep 11: a second run beside a live checkpointed run exits 1 with no code; `state reset-chunks` in the same situation gives RIVET_STATE_RUN_IN_PROGRESS (5)'),
    _open("live_operator_contract::open_defect_a_second_run_beside_a_live_checkpointed_run_is_refused_by_code_mssql",
          'refusal contract: the invocation ended with no RIVET_* code (exit 1), expected [RIVET_STATE_RUN_IN_PROGRESS] (exit 5)',
          'Sweep 11: a second run beside a live checkpointed run exits 1 with no code; `state reset-chunks` in the same situation gives RIVET_STATE_RUN_IN_PROGRESS (5)'),
    _open("live_operator_contract::open_defect_plan_fails_over_a_table_that_does_not_exist_postgres",
          '`plan` over a table that does not exist exited 0 and sealed the artifact',
          'Sweep 10: `plan` cannot read the source, prints a WARN, exits 0 and seals a plan that `apply` then fails'),
    _open("live_operator_contract::open_defect_plan_fails_over_a_table_that_does_not_exist_mysql",
          '`plan` over a table that does not exist exited 0 and sealed the artifact',
          'Sweep 10: `plan` cannot read the source, prints a WARN, exits 0 and seals a plan that `apply` then fails'),
    _open("live_operator_contract::open_defect_plan_fails_over_a_table_that_does_not_exist_mssql",
          '`plan` over a table that does not exist exited 0 and sealed the artifact',
          'Sweep 10: `plan` cannot read the source, prints a WARN, exits 0 and seals a plan that `apply` then fails'),
    _open("live_operator_contract::open_defect_plan_fails_over_a_table_that_does_not_exist_oracle",
          '`plan` over a table that does not exist exited 0 and sealed the artifact',
          'Sweep 10: `plan` cannot read the source, prints a WARN, exits 0 and seals a plan that `apply` then fails'),
    _open("live_operator_contract::open_defect_an_unusable_state_url_is_refused_postgres",
          '`RIVET_STATE_URL=postgre://...` (a scheme rivet does not know) ran with exit 0 on a SQLite state beside the config',
          'Sweep 9: a `RIVET_STATE_URL` that does not start with `postgres` is ignored with no warning and the run keeps a SQLite state beside the config'),
    _open("live_operator_contract::open_defect_an_unusable_state_url_is_refused_mysql",
          '`RIVET_STATE_URL=postgre://...` (a scheme rivet does not know) ran with exit 0 on a SQLite state beside the config',
          'Sweep 9: a `RIVET_STATE_URL` that does not start with `postgres` is ignored with no warning and the run keeps a SQLite state beside the config'),
    _open("live_operator_contract::open_defect_an_unusable_state_url_is_refused_mssql",
          '`RIVET_STATE_URL=postgre://...` (a scheme rivet does not know) ran with exit 0 on a SQLite state beside the config',
          'Sweep 9: a `RIVET_STATE_URL` that does not start with `postgres` is ignored with no warning and the run keeps a SQLite state beside the config'),
    _open("live_operator_contract::open_defect_an_unusable_state_url_is_refused_oracle",
          '`RIVET_STATE_URL=postgre://...` (a scheme rivet does not know) ran with exit 0 on a SQLite state beside the config',
          'Sweep 9: a `RIVET_STATE_URL` that does not start with `postgres` is ignored with no warning and the run keeps a SQLite state beside the config'),
    _open("live_operator_contract::open_defect_deleting_a_corrupt_cdc_checkpoint_accepts_a_new_anchor_mysql",
          'refuse-then-remedy: remedy `delete it to accept a new anchor from a fresh snapshot` ended with no RIVET_* code (exit 1), expected exit 0 and the source delivered',
          'Sweep 13: the corrupt-checkpoint refusal says to delete the file; after a baseline the next run refuses the missing checkpoint (`prior-run evidence exists`)'),
    _open("live_operator_contract::open_defect_a_corrupt_cdc_checkpoint_is_refused_by_code_mysql",
          'refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_CHECKPOINT_INVALID] (exit 5)',
          'Sweep (exit-code contract): a checkpoint that is not JSON is refused with exit 1 and no code; the registry has RIVET_SOURCE_CDC_CHECKPOINT_INVALID (5), given for valid JSON of the wrong shape'),
    _open("live_operator_contract::open_defect_deleting_a_corrupt_cdc_checkpoint_accepts_a_new_anchor_mssql",
          'refuse-then-remedy: remedy `delete it to accept a new anchor from a fresh snapshot` ended with no RIVET_* code (exit 1), expected exit 0 and the source delivered',
          'Sweep 13: the corrupt-checkpoint refusal says to delete the file; after a baseline the next run refuses the missing checkpoint (`prior-run evidence exists`)'),
    _open("live_operator_contract::open_defect_a_corrupt_cdc_checkpoint_is_refused_by_code_mssql",
          'refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_CHECKPOINT_INVALID] (exit 5)',
          'Sweep (exit-code contract): a checkpoint that is not JSON is refused with exit 1 and no code; the registry has RIVET_SOURCE_CDC_CHECKPOINT_INVALID (5), given for valid JSON of the wrong shape'),
    _open("live_operator_contract::open_defect_a_cdc_truncate_is_refused_by_code_mysql",
          'refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_TRUNCATED] (exit 5)',
          'Sweep (exit-code contract): a TRUNCATE in the stream is refused with exit 1 and no code on this engine; the registry has RIVET_SOURCE_CDC_TRUNCATED (5), which Oracle gives'),
    _open("live_operator_contract::open_defect_a_cdc_truncate_is_refused_by_code_postgres",
          'refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_TRUNCATED] (exit 5)',
          'Sweep (exit-code contract): a TRUNCATE in the stream is refused with exit 1 and no code on this engine; the registry has RIVET_SOURCE_CDC_TRUNCATED (5), which Oracle gives'),
    _open("live_operator_contract::open_defect_a_dropped_slot_is_refused_by_code_postgres",
          'refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_LOG_GAP] (exit 5)',
          "Sweep 17: a slot dropped under a baselined stream is refused with a named cause, exit 1 and no code; the registry's code for a log that is gone past the stream's position is RIVET_SOURCE_CDC_LOG_GAP (5)"),
    _open("live_operator_contract::open_defect_a_refused_cdc_run_on_a_missing_table_leaves_no_slot_postgres",
          'assertion `left == right` failed: a PostgreSQL CDC run refused for a table that does not exist left its replication slot',
          'Sweep 15: the slot is created before the table is checked, and the refused run leaves it inactive, pinning WAL'),
    _open("live_operator_contract::open_defect_doctor_is_not_green_where_the_cdc_run_refuses_wal_level_postgres",
          'doctor and run disagree: doctor reported all_ok, the run refused',
          'Sweep (advice parity): `doctor` reports `All checks passed` for a CDC export on a `wal_level=replica` server, which `run` refuses; the MySQL doctor fails the equivalent case'),
    _open("live_operator_contract::open_defect_removing_page_size_runs_after_the_heterogeneous_id_refusal_mongo",
          'refuse-then-remedy: remedy `Remove `page_size`` ended with [RIVET_STATE_INTERRUPTED_RUN_OWNER_MISMATCH] (exit 5), expected exit 0 and the source delivered',
          'Sweep 14: the refused resume has already claimed the cursor row, so the remedy the refusal names (a full scan without `page_size`) is refused as an interrupted run of another mode; exit 0 on v0.31.0'),
    _open("live_operator_contract::open_defect_a_run_that_never_connected_keeps_the_export_complete_mongo",
          'a run that never connected left `_SUCCESS` withdrawn and manifest.json `failed` over a complete export',
          'Sweep 8 (owner decision 2026-10-07): a run that fails before its first write still rewrites manifest.json to failed and deletes `_SUCCESS`; it must leave both alone'),
    _open("live_operator_contract::open_defect_validate_fails_on_a_missing_bucket_s3",
          '`validate` on a bucket that does not exist exited 0 with `status: legacy_run`',
          'Sweep 5: `validate` reads a missing bucket as a prefix with no manifest (`legacy_run`) and exits 0'),
    _open("live_operator_contract::open_defect_validate_fails_on_a_missing_bucket_gcs",
          '`validate` on a bucket that does not exist exited 0 with `status: legacy_run`',
          'Sweep 5: `validate` reads a missing bucket as a prefix with no manifest (`legacy_run`) and exits 0'),
    _open("live_operator_contract::open_defect_validate_fails_on_a_missing_bucket_azure",
          '`validate` on a bucket that does not exist exited 0 with `status: legacy_run`',
          'Sweep 5: `validate` reads a missing bucket as a prefix with no manifest (`legacy_run`) and exits 0'),
    _open("live_operator_contract::open_defect_a_bounded_cdc_run_refused_on_a_standby_leaves_nothing_and_its_remedy_runs_postgres",
          "rig oracle: success-marker: ",
          "Sweep 15 (standby twin): the bounded run refused on a PostgreSQL standby has already created its slot, written the snapshot baseline with `_SUCCESS` and stored a `cdc_snapshot` row; the refusal must come before the anchor"),
    _open("live_operator_contract::open_defect_a_cdc_collection_drop_is_refused_by_code_mongo",
          "refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_TRUNCATED] (exit 5)",
          "Devbox sweep row 296: a dropped captured collection is refused with exit 1 and no code; Oracle gives RIVET_SOURCE_CDC_TRUNCATED (5) for the same loss"),
    _open("live_operator_contract::open_defect_a_change_table_cleaned_past_the_checkpoint_before_the_first_changes_run_is_refused_by_code_mssql",
          "rig oracle: VALUES: 1 source row(s) not delivered, 1 delivered row(s) not in the source; differing column(s) ['v'] of ['id', 'v']; source-only ['[[\"num\", \"1\"], [\"num\", \"99\"]]']; delivered-only ['[[\"num\", \"1\"], [\"num\", \"1\"]]']",
          "Sweep 6: with the checkpoint still `pinned`, a resume position below `fn_cdc_get_min_lsn` is not refused; the run exits 0 and the cleaned changes are lost. Its fix is its own PR"),
    _open("live_operator_contract::open_defect_a_corrupt_cdc_checkpoint_is_refused_by_code_mongo",
          "refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_CHECKPOINT_INVALID] (exit 5)",
          "Sweep (exit-code contract): a checkpoint that is not JSON is refused with exit 1 and no code; the registry has RIVET_SOURCE_CDC_CHECKPOINT_INVALID (5), given for valid JSON of the wrong shape"),
    _open("live_operator_contract::open_defect_a_corrupt_cdc_checkpoint_is_refused_by_code_oracle",
          "refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_CHECKPOINT_INVALID] (exit 5)",
          "Sweep (exit-code contract): a checkpoint that is not JSON is refused with exit 1 and no code; the registry has RIVET_SOURCE_CDC_CHECKPOINT_INVALID (5), given for valid JSON of the wrong shape"),
    _open("live_operator_contract::open_defect_a_corrupt_cdc_checkpoint_is_refused_by_code_postgres",
          "refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_CHECKPOINT_INVALID] (exit 5)",
          "Sweep (exit-code contract): a checkpoint that is not JSON is refused with exit 1 and no code; the registry has RIVET_SOURCE_CDC_CHECKPOINT_INVALID (5), given for valid JSON of the wrong shape"),
    _open("live_operator_contract::open_defect_a_dropped_slot_after_a_changes_run_is_refused_by_code_postgres",
          "refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_LOG_GAP] (exit 5)",
          "Sweep 17: a slot dropped under a stream that already drained changes is refused with a named cause but exit 1 and no code; owner decision 2026-10-07: RIVET_SOURCE_CDC_LOG_GAP (5)"),
    _open("live_operator_contract::open_defect_a_second_concurrent_full_run_does_not_double_the_prefix_mongo",
          "rig oracle: COUNT(*): source 300000, delivered 600000",
          "Sweep 4: a second `full` run beside a live one is not refused; both exit 0 and the prefix holds every key twice"),
    _open("live_operator_contract::open_defect_a_second_run_beside_a_live_checkpointed_run_is_refused_by_code_oracle",
          "refusal contract: the invocation ended with no RIVET_* code (exit 1), expected [RIVET_STATE_RUN_IN_PROGRESS] (exit 5)",
          "Sweep 11: a second run beside a live checkpointed run exits 1 with no code; `state reset-chunks` in the same situation gives RIVET_STATE_RUN_IN_PROGRESS (5)"),
    _open("live_operator_contract::open_defect_a_second_run_beside_a_live_resumable_run_is_refused_by_code_mongo",
          "refusal contract: the invocation ended with no RIVET_* code (exit 1), expected [RIVET_STATE_RUN_IN_PROGRESS] (exit 5)",
          "Sweep 11: a second run beside a live checkpointed run exits 1 with no code; `state reset-chunks` in the same situation gives RIVET_STATE_RUN_IN_PROGRESS (5)"),
    _open("live_operator_contract::open_defect_a_stale_chunk_checkpoint_is_not_adopted_after_a_finished_run_oracle",
          "rig oracle: VALUES: 15 source row(s) not delivered, 15 delivered row(s) not in the source; differing column(s) ['v'] of ['id', 'v']; source-only ['[[\"num\", \"1\"], [\"num\", \"1001\"]]', '[[\"num\", \"10\"], [\"num\", \"1010\"]]', '[[\"num\", \"11\"], [\"num\", \"1011\"]]', '[[\"num\", \"12\"], [\"num\", \"1012\"]]', '[[\"num\", \"",
          "Sweep 1: a chunk checkpoint left by a crashed run is resumed after a later run (checkpoint off) finished the export, so the parts written before the crash are declared again with exit 0"),
    _open("live_operator_contract::open_defect_an_unusable_state_url_is_refused_mongo",
          "`RIVET_STATE_URL=postgre://...` (a scheme rivet does not know) ran with exit 0 on a SQLite state beside the config",
          "Sweep 9: `RIVET_STATE_URL` with a scheme rivet does not know is ignored without a warning and the run uses a SQLite state beside the config"),
    _open("live_operator_contract::open_defect_binlogs_purged_past_the_checkpoint_after_a_changes_run_are_refused_by_code_mysql",
          "refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_LOG_GAP] (exit 5)",
          "Sweep 17: binlogs purged past the checkpoint are refused with the raw `MySqlError { ERROR 1236 ... }`, exit 1 and no code; the registry has RIVET_SOURCE_CDC_LOG_GAP (5)"),
    _open("live_operator_contract::open_defect_binlogs_purged_past_the_checkpoint_before_the_first_changes_run_are_refused_by_code_mysql",
          "refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_LOG_GAP] (exit 5)",
          "Sweep 17: binlogs purged past the checkpoint are refused with the raw `MySqlError { ERROR 1236 ... }`, exit 1 and no code; the registry has RIVET_SOURCE_CDC_LOG_GAP (5)"),
    _open("live_operator_contract::open_defect_an_oplog_rolled_past_the_checkpoint_before_the_first_changes_run_is_refused_by_code_mongo",
          "refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_LOG_GAP] (exit 5)",
          "Gaps round three: an oplog rolled past the resume token (ChangeStreamHistoryLost, error 286) is refused behind the blanket setup hint (`if this is a setup error: MongoDB change streams require a replica set`), exit 1 and no code; the registry has RIVET_SOURCE_CDC_LOG_GAP (5)"),
    _open("live_operator_contract::open_defect_an_oplog_rolled_past_the_checkpoint_after_a_changes_run_is_refused_by_code_mongo",
          "refuse-then-remedy: cycle 1 ended with no RIVET_* code (exit 1), expected [RIVET_SOURCE_CDC_LOG_GAP] (exit 5)",
          "Gaps round three: an oplog rolled past the resume token (ChangeStreamHistoryLost, error 286) is refused behind the blanket setup hint (`if this is a setup error: MongoDB change streams require a replica set`), exit 1 and no code; the registry has RIVET_SOURCE_CDC_LOG_GAP (5)"),
    _open("live_operator_contract::open_defect_cdc_to_stdout_emits_each_change_once_postgres",
          "assertion `left == right` failed: three `rivet cdc` runs to stdout over three changes emitted [3, 3, 3] events",
          "Sweep 16: `rivet cdc` to stdout on PostgreSQL never advances the slot, so every run re-emits every change since the slot was created, with or without `--checkpoint`"),
    _open("live_cdc_cli_surface::open_defect_pg_cdc_cli_rollover_1_delivers_the_pending_changes",
          "rig oracle: COUNT(*): source 3, delivered 0",
          "Gaps round four: on PostgreSQL every `rivet cdc --output <dir> --rollover 1` run exits 0 with a Success manifest of 0 rows while committed changes are pending (two runs in a row over three single-row commits; `--rollover 2` delivers them); no work item yet"),
    _open("live_operator_contract::open_defect_check_names_the_strategy_run_uses_for_chunked_with_no_column_mssql",
          "`check` said `Strategy: chunked` and `run` exported 40 rows as one unchunked part",
          "Sweep 20: for `mode: chunked` with no chunk column `check` prints `Strategy: chunked(id, size=100000)` with `column: ?`, and `run` exports the table as one unchunked pass"),
    _open("live_operator_contract::open_defect_check_names_the_strategy_run_uses_for_chunked_with_no_column_mysql",
          "`check` said `Strategy: chunked` and `run` exported 40 rows as one unchunked part",
          "Sweep 20: for `mode: chunked` with no chunk column `check` prints `Strategy: chunked(id, size=100000)` with `column: ?`, and `run` exports the table as one unchunked pass"),
    _open("live_operator_contract::open_defect_check_names_the_strategy_run_uses_for_chunked_with_no_column_oracle",
          "`check` said `Strategy: chunked` and `run` exported 40 rows as one unchunked part",
          "Sweep 20: for `mode: chunked` with no chunk column `check` prints `Strategy: chunked(id, size=100000)` with `column: ?`, and `run` exports the table as one unchunked pass"),
    _open("live_operator_contract::open_defect_check_names_the_strategy_run_uses_for_chunked_with_no_column_postgres",
          "`check` said `Strategy: chunked` and `run` exported 40 rows as one unchunked part",
          "Sweep 20: for `mode: chunked` with no chunk column `check` prints `Strategy: chunked(id, size=100000)` with `column: ?`, and `run` exports the table as one unchunked pass"),
    _open("live_operator_contract::open_defect_deleting_a_corrupt_cdc_checkpoint_accepts_a_new_anchor_mongo",
          "refuse-then-remedy: remedy `delete it to accept a new anchor from a fresh snapshot` ended with no RIVET_* code (exit 1), expected exit 0 and the source delivered",
          "Sweep 13: the corrupt-checkpoint refusal says to delete the file; after a baseline the next run refuses the missing checkpoint (`prior-run evidence exists`)"),
    _open("live_operator_contract::open_defect_deleting_a_corrupt_cdc_checkpoint_accepts_a_new_anchor_oracle",
          "refuse-then-remedy: remedy `delete it to accept a new anchor from a fresh snapshot` ended with no RIVET_* code (exit 1), expected exit 0 and the source delivered",
          "Sweep 13: the corrupt-checkpoint refusal says to delete the file; after a baseline the next run refuses the missing checkpoint (`prior-run evidence exists`)"),
    _open("live_operator_contract::open_defect_doctor_is_not_green_where_the_cdc_run_refuses_a_replica_that_does_not_relog_mysql",
          "doctor and run disagree: doctor reported all_ok, the run refused",
          "Devbox sweep row 330: `doctor` reports all checks passed for a CDC export on a replica with `log_replica_updates = OFF`, which `run` refuses"),
    _open("live_operator_contract::open_defect_init_cdc_writes_the_capture_instance_the_catalog_holds_mssql",
          "assertion `left == right` failed: `rivet init --mode cdc` wrote a capture instance cdc.change_tables does not hold for dbo.oc_initc_",
          "Sweep 19: `rivet init --mode cdc` on SQL Server derives `capture_instance: dbo_<table>` and does not read `cdc.change_tables`, so the run refuses an instance the catalog does not know"),
    _open("live_operator_contract::open_defect_plan_fails_over_a_collection_that_does_not_exist_mongo",
          "`plan` over a table that does not exist exited 0 and sealed the artifact",
          "Sweep 10: `plan` over a relation that does not exist exits 0 and seals the artifact with only a WARN; `apply` then fails"),
    _open("live_operator_contract::open_defect_range_chunking_takes_a_number_19_key_oracle",
          "range chunking refused an Oracle NUMBER(19) integer key (exit Some(1))",
          "2026-10-06 finding: range chunking refuses an Oracle `NUMBER(19)` primary key (scale 0) as not integer-family, while it takes `NUMBER(18)`"),
    _open("live_operator_contract::open_defect_resume_force_runs_over_a_complete_prefix_oracle",
          "refuse-then-remedy: remedy `Pass --force to override` ended with no RIVET_* code (exit 1), expected exit 0 and the source delivered",
          "Sweep 12: the `--resume` refusal over a complete prefix says `Pass --force to override`; `--resume --force` then exits 1 `nothing to continue`"),
    _open("live_operator_contract::open_defect_run_validate_does_not_exit_0_over_a_failed_validation_mongo",
          "`run --validate` exited 0 with `validated: FAIL`",
          "Sweep 2: `run --validate` prints `validated: FAIL` and exits 0 with `status: success`; standalone `validate` exits 3"),
    _open("live_operator_contract::open_defect_the_config_init_writes_runs_cdc_on_a_standby_postgres",
          "rig oracle: success-marker: ",
          "Sweep E2: `rivet init --mode cdc` against a PostgreSQL standby writes `until_current: true`, which the run refuses on a standby, after it has already anchored"),
    KnownRed('upgrade[oracle/cdc-load]: cycle1/load: prev exit 1: Error: config has no top-level `load:` block',
             "Oracle CDC does not load yet (ADR-0037; the Oracle GA work). The previous release's `rivet init --mode cdc` writes no `load:` block, and this cell still drives the previous release through `load`, which refuses. `upgrade[oracle/cdc-load/init=this]` grades what the scaffold does promise (the baseline Parquet equals the source). The cycle stays unsupported until Oracle CDC loads",
             "2026-10-31"),
    KnownRed('upgrade[oracle/cdc-load/tz=Asia/Tokyo]: cycle1/load: prev exit 1: Error: config has no top-level `load:` block',
             "Oracle CDC does not load yet (ADR-0037; the Oracle GA work). The previous release's `rivet init --mode cdc` writes no `load:` block, and this cell still drives the previous release through `load`, which refuses. `upgrade[oracle/cdc-load/init=this]` grades what the scaffold does promise (the baseline Parquet equals the source). The cycle stays unsupported until Oracle CDC loads",
             "2026-10-31"),
    KnownRed('sentinels[rivet_sent_ts9/full]: SUCCEEDED WITH A CHANGED VALUE: `V` differs',
             "Oracle TIMESTAMP(9) is delivered at microseconds today: docs/type-capability-matrix.yaml's oracle TIMESTAMP(9) row is a known_defect (exact native is Timestamp(ns), ADR-0038 CP1, Oracle engine step), so the 1 ns sentinel lands truncated",
             "2026-10-31"),
    KnownRed('sentinels[rivet_sent_ts9/keyset]: SUCCEEDED WITH A CHANGED VALUE: `V` differs',
             "Oracle TIMESTAMP(9) is delivered at microseconds today: docs/type-capability-matrix.yaml's oracle TIMESTAMP(9) row is a known_defect (exact native is Timestamp(ns), ADR-0038 CP1, Oracle engine step), so the 1 ns sentinel lands truncated",
             "2026-10-31"),
)


def match(msg: str, today: _dt.date | None = None) -> tuple[KnownRed | None, bool]:
    """The entry `msg` matches and whether it is still in date."""
    today = today or _dt.date.today()
    for k in KNOWN_RED:
        if k.match in msg:
            return k, today <= _dt.date.fromisoformat(k.expires)
    return None, False
