-- Parallel-keyset sparse GOLDEN fixture — MySQL 8.0+.
-- 10,000,000 rows, wide, sparse key id = n*997. Same rows as the PG/MSSQL
-- fixtures (all columns derived from n). Heavy: seed on the devbox.
-- 10M rows are generated by a 10000 x 1000 cross join of two number CTEs
-- (a straight recursive CTE to 10M is impractically slow / depth-capped).
SET SESSION cte_max_recursion_depth = 20000;

DROP TABLE IF EXISTS keyset_sparse;
CREATE TABLE keyset_sparse (
    id          BIGINT        PRIMARY KEY,   -- sparse keyset key (n*997)
    grp         INT           NOT NULL,
    amount      DECIMAL(18,4) NOT NULL,
    ratio       DOUBLE        NOT NULL,
    label       VARCHAR(64)   NOT NULL,
    descr       VARCHAR(200)  NOT NULL,
    code        CHAR(10)      NOT NULL,
    flag        TINYINT(1)    NOT NULL,
    created_at  DATETIME      NOT NULL,
    updated_on  DATE          NOT NULL,
    big_n       BIGINT        NOT NULL,
    note        TEXT          NOT NULL
) ENGINE=InnoDB;

INSERT INTO keyset_sparse
WITH RECURSIVE
  seq10k(a) AS (SELECT 0 UNION ALL SELECT a + 1 FROM seq10k WHERE a < 9999),
  seq1k(b)  AS (SELECT 0 UNION ALL SELECT b + 1 FROM seq1k  WHERE b < 999)
SELECT
    n * 997                                        AS id,
    n % 1000                                       AS grp,
    CAST((n % 100000) + (n % 10000) / 10000.0 AS DECIMAL(18,4)) AS amount,
    n / 7.0                                        AS ratio,
    CONCAT('lbl-', n % 500)                        AS label,
    CONCAT('row-', n, '-payload')                  AS descr,
    LPAD(HEX(n), 10, '0')                          AS code,
    n % 2 = 0                                       AS flag,
    DATE_ADD('2020-01-01 00:00:00', INTERVAL n SECOND)   AS created_at,
    DATE_ADD('2020-01-01', INTERVAL (n % 3650) DAY)      AS updated_on,
    CAST(n AS SIGNED) * CAST(n AS SIGNED)          AS big_n,
    CONCAT('note-', n)                             AS note
FROM (SELECT a * 1000 + b + 1 AS n FROM seq10k CROSS JOIN seq1k) t;

SELECT COUNT(*) AS rows, MIN(id) AS min_id, MAX(id) AS max_id,
       ROUND((MAX(id) - MIN(id)) / COUNT(*), 1) AS span_per_row
FROM keyset_sparse;
