//! INIT: a config `rivet init` wrote, used from its own directory as init's next-steps text says.

use crate::common::runner::{run_rivet, run_rivet_in_dir};

/// A config generated by `rivet init`, never rendered or edited by the harness.
pub struct InitConfig {
    dir: tempfile::TempDir,
    url: String,
    /// What `rivet init` itself answered.
    pub init: std::process::Output,
}

impl InitConfig {
    /// `rivet init --source <url> <args…> --output <own dir>/rivet.yaml`.
    pub fn generate(url: &str, args: &[&str]) -> Self {
        let dir = tempfile::tempdir().expect("init config dir");
        let cfg = dir.path().join("rivet.yaml").display().to_string();
        let mut argv = vec!["init", "--source", url];
        argv.extend_from_slice(args);
        argv.extend(["--output", cfg.as_str()]);
        let init = run_rivet(&argv);
        InitConfig {
            dir,
            url: url.to_string(),
            init,
        }
    }

    /// The generated YAML; panics with init's own words when it wrote none.
    pub fn yaml(&self) -> String {
        std::fs::read_to_string(self.dir.path().join("rivet.yaml")).unwrap_or_else(|_| {
            panic!(
                "`rivet init` wrote no config (exit {:?}):\n{}",
                self.init.status.code(),
                String::from_utf8_lossy(&self.init.stderr)
            )
        })
    }

    /// The first `key: value` of the generated YAML.
    pub fn field(&self, key: &str) -> Option<String> {
        let want = format!("{key}:");
        self.yaml().lines().find_map(|l| {
            let v = l.trim().strip_prefix(&want)?;
            let v = v.split(" #").next().unwrap_or(v).trim();
            (!v.is_empty()).then(|| v.trim_matches(['"', '\'']).to_string())
        })
    }

    /// `rivet <args…> --config rivet.yaml` from the config's directory with `DATABASE_URL` set, graded by the default oracle.
    pub fn cli(&self, args: &[&str]) -> std::process::Output {
        self.yaml();
        let mut argv = args.to_vec();
        argv.extend(["--config", "rivet.yaml"]);
        run_rivet_in_dir(self.dir.path(), &argv, &[("DATABASE_URL", &self.url)])
    }

    /// The directory the config lives in (its relative destination and checkpoint resolve here).
    pub fn dir(&self) -> &std::path::Path {
        self.dir.path()
    }
}
