# typed: false
# frozen_string_literal: true

# Generated by dev/update_homebrew_formula.sh — do not edit checksums by hand.
# Re-run the script after each release.

class Rivet < Formula
  desc "CLI to export PostgreSQL and MySQL to Parquet/CSV (local, S3, GCS)"
  homepage "https://github.com/panchenkoai/rivet"
  version "0.2.0-beta.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.2.0-beta.6/rivet-v0.2.0-beta.6-aarch64-apple-darwin.tar.gz"
      sha256 "7c511675522de157b0d671143ec3b2890cb7863bbe24c70383d7c129a4382db2"
    end
    on_intel do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.2.0-beta.6/rivet-v0.2.0-beta.6-x86_64-apple-darwin.tar.gz"
      sha256 "ad53d22bea57d51a39b96299d040a472b0e587791281856c9eda70dcdc859eed"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.2.0-beta.6/rivet-v0.2.0-beta.6-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4fc3800d378b5409ef4191b4874008632dd88c4f055750ae9abece61f39602c5"
    end
    on_intel do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.2.0-beta.6/rivet-v0.2.0-beta.6-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6bb871a52b2db3b5f5a74ff41d45e3f2c6a2ae9cd57847f879cdff21cf4a89be"
    end
  end

  def install
    bin.install "rivet"
  end

  test do
    system "#{bin}/rivet", "--version"
  end
end
