# typed: false
# frozen_string_literal: true

# Generated by dev/update_homebrew_formula.sh — do not edit checksums by hand.
# Re-run the script after each release.

class Rivet < Formula
  desc "CLI to export PostgreSQL and MySQL to Parquet/CSV (local, S3, GCS)"
  homepage "https://github.com/panchenkoai/rivet"
  version "0.2.0-beta.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.2.0-beta.2/rivet-v0.2.0-beta.2-aarch64-apple-darwin.tar.gz"
      sha256 "48bc17f1c2abb5a960663cddc57664d1409058d5b04821168cde0840493cb1a2"
    end
    on_intel do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.2.0-beta.2/rivet-v0.2.0-beta.2-x86_64-apple-darwin.tar.gz"
      sha256 "e9de5bc57453ad789785e577c2f6a5f1ef557a29692d29649e7f9b110010a15b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.2.0-beta.2/rivet-v0.2.0-beta.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "07e48bc0d8bc9f576d834bd4f7a59cef2c4c9db33b4ea8aa856372be1349f54e"
    end
    on_intel do
      url "https://github.com/panchenkoai/rivet/releases/download/v0.2.0-beta.2/rivet-v0.2.0-beta.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7c20d0f58e4975ee9f47968d8f289ce58b5ca96394556b60460baabf0557b047"
    end
  end

  def install
    bin.install Dir["rivet-*/rivet"].first => "rivet"
  end

  test do
    system "#{bin}/rivet", "--version"
  end
end
